- type: entity
  id: PrinterDocMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: document printer machine board
  description: A machine printed circuit board for an document printer
  components:
    - type: MachineBoard
      prototype: PrinterDoc
      stackRequirements:
        # Manipulator: 4 # <Onyx-TieredMachineParts-edited>
        Glass: 1
      # <Onyx-TieredMachineParts>
      partRequirements:
        Servo: 4
      # </Onyx-TieredMachineParts>
