# Content adapted from Goob Station (https://github.com/Goob-Station/Goob-Station), licensed under AGPL-3.0-or-later.

- type: entity
  id: LaserSniper
  parent: BasicHitscan
  categories: [ HideSpawnMenu ]
  components:
  - type: HitscanBasicDamage
    damage:
      types:
        Heat: 30
        Shock: 10
  - type: HitscanBasicVisuals
    muzzleFlash:
      sprite: Objects/Weapons/Guns/Projectiles/projectiles.rsi
      state: muzzle_blue
    travelFlash:
      sprite: _Onyx/Objects/Weapons/Guns/Projectiles/heavy_pulse.rsi
      state: beam_blue_heavy
    impactFlash:
      sprite: Objects/Weapons/Guns/Projectiles/projectiles.rsi
      state: impact_blue

- type: entity
  id: RedMediumSplitLaser
  parent: BasicHitscan
  categories: [ HideSpawnMenu ]
  components:
  - type: HitscanBasicDamage
    damage:
      types:
        Heat: 17
        Shock: 2
  - type: HitscanBasicVisuals
    muzzleFlash:
      sprite: Objects/Weapons/Guns/Projectiles/projectiles.rsi
      state: muzzle_laser
    travelFlash:
      sprite: Objects/Weapons/Guns/Projectiles/projectiles.rsi
      state: beam
    impactFlash:
      sprite: Objects/Weapons/Guns/Projectiles/projectiles.rsi
      state: impact_laser

- type: entity
  name: heavy laser bolt
  id: BulletLaserHeavy
  parent: BulletLaser
  categories: [ HideSpawnMenu ]
  components:
  - type: Projectile
    impactEffect: BulletImpactEffectOrangeDisabler
    damage:
      types:
        Heat: 8

- type: entity
  name: heavy laser bolt
  id: BulletLaserHeavyStructural
  parent: BulletLaserHeavy
  categories: [ HideSpawnMenu ]
  components:
  - type: Projectile
    impactEffect: BulletImpactEffectOrangeDisabler
    damage:
      types:
        Heat: 12
        Structural: 10

- type: entity
  name: heavy laser barrage
  id: BulletLaserSpreadHeavy
  parent: BulletLaserHeavy
  categories: [ HideSpawnMenu ]
  components:
  - type: ProjectileSpread
    proto: BulletLaserHeavyStructural
    count: 6
    spread: 30
