- type: job
  id: Virologist
  name: job-name-virologist
  description: job-description-virologist
  playTimeTracker: JobVirologist
  requirements:
  - !type:DepartmentTimeRequirement
    department: Medical
    time: 4h
  startingGear: VirologistGear
  icon: JobIconVirologist
  supervisors: job-supervisors-cmo
  guides: [ MedicalDoctor, Medical, Medicine, Virology ]
  contracts:
  - DocumentContractEmploymentMedical
  access:
  - Medical
  - Maintenance
  extendedAccess:
  - Chemistry
  special:
  - !type:AddComponentSpecial
    components:
    - type: SurgerySpeedModifier
      speedModifier: 1.75

- type: startingGear
  id: VirologistGear
  equipment:
    ears: ClothingHeadsetMedical
    eyes: ClothingEyesHudViro
    belt: ClothingBeltMedicalFilled

- type: chameleonOutfit
  id: VirologistChameleonOutfit
  job: Virologist
  equipment:
    ears: ClothingHeadsetMedical
    eyes: ClothingEyesHudViro
    belt: ClothingBeltMedicalFilled
