- type: entity
  name: polymer baton
  parent: [BaseItem, BaseSecurityContraband]
  id: PolymerBaton
  description: A lightweight, durable baton made from advanced polymers. Delivers less-than-lethal force for compliance and control.
  components:
  - type: Sprite
    sprite: _Onyx/Objects/Weapons/Melee/polybaton.rsi
    state: icon
    scale: 0.9, 0.9
  - type: Clothing
    sprite: _Onyx/Objects/Weapons/Melee/polybaton.rsi
    quickEquip: false
    slots:
    - belt
  - type: MeleeWeapon
    wideAnimationRotation: -135
    damage:
      types:
        Blunt: 12
    soundHit:
      path: /Audio/_Onyx/Weapons/Baton/woodhit.ogg
  - type: StaminaDamageOnHit
    damage: 15
  - type: MeleeThrowOnHit
    distance: 1
    speed: 5
  - type: Item
    size: Normal
    storedRotation: -75
    shape:
    - 0,0,1,2
  - type: Tag
    tags:
    - SecBeltEquip

- type: entity
  parent: [ BaseItem, BaseSecurityContraband, ClothingBeltBase ]
  id: PoliceBaton
  name: police baton
  description: A wooden truncheon for beating criminal scum.
  components:
  - type: Sprite
    sprite: _Onyx/Objects/Weapons/Melee/police_baton.rsi
    state: icon
  - type: Clothing
    sprite: _Onyx/Objects/Weapons/Melee/police_baton.rsi
  - type: Item
    size: Normal
    shape:
    - 0,0,1,2
  - type: MeleeWeapon
    attackRate: 0.8
    damage:
      types:
        Blunt: 10
    angle: 0
    animation: WeaponArcThrust
  - type: UseDelay
    delays:
      hit:
        length: 2
  - type: UseDelayBlockMelee
    delays:
    - hit
  - type: StaminaDamageOnHit
    damage: 35
    sound: /Audio/_Onyx/Weapons/Baton/woodhit.ogg
  - type: StaticPrice
    price: 65

- type: entity
  id: SpearTelescopic
  parent: [BaseItem, BaseSecurityContraband]
  name: telescopic spear
  description: A compact, throwable spear with a retractable shaft. Designed for both melee and ranged use.
  components:
  - type: Item
    size: Normal
    storedRotation: 45
    heldPrefix: off
    shape:
    - 0,0,3,0
  - type: Sprite
    sprite: _Onyx/Objects/Weapons/Melee/telespear.rsi
    layers:
    - state: icon-off
      map: [ "enum.ToggleableVisuals.Layer" ]
  - type: Clothing
    sprite: _Onyx/Objects/Weapons/Melee/telespear.rsi
    slots:
    - Back
    - suitStorage
  - type: Fixtures
    fixtures:
      fix1:
        shape: !type:PolygonShape
          vertices:
          - -0.08,-0.06
          - -0.06,-0.08
          - 0.40,0.30
          - 0.30,0.40
        density: 20
        mask:
        - ItemMask
        restitution: 0.3
        friction: 0.2
  - type: EmbeddableProjectile
    offset: -0.15,0.0
  - type: LandAtCursor
  - type: ThrowingAngle
    angle: 225
  - type: ItemToggle
    onActivate: false
    soundActivate:
      path: /Audio/Weapons/telescopicon.ogg
    soundDeactivate:
      path: /Audio/Weapons/telescopicoff.ogg
  - type: ComponentToggler
    components:
    - type: Sharp
    - type: DisarmMalus
      malus: 0.6
    - type: Wieldable
    - type: DamageOtherOnHit
      damage:
        types:
          Piercing: 36
  - type: DynamicWieldCleanup
  - type: ItemToggleSize
    activatedSize: Ginormous
  - type: ItemToggleMeleeWeapon
    activatedSoundOnHit:
      path: /Audio/Weapons/bladeslice.ogg
    activatedDamage:
      types:
        Piercing: 18
  - type: IncreaseDamageOnWield
    damage:
      types:
        Piercing: 6
  - type: MeleeWeapon
    range: 2.2
    attackRate: 0.8
    damage:
      types:
        Blunt: 5
        Piercing: 5
    soundHit:
      collection: MetalThud
  - type: Appearance
  - type: GenericVisualizer
    visuals:
      enum.ToggleableVisuals.Enabled:
        enum.ToggleableVisuals.Layer:
          True: { state: icon }
          False: { state: icon-off }
  - type: Tag
    tags:
    - SecBeltEquip
