// Space Onyx
// Copyright (C) 2026 Space Onyx contributors
//
// This file is licensed under AGPL-3.0-or-later.
// See LICENSES for the full license text.

using System.Linq;
using System.Numerics;
using Content.Client.Lobby;
using Content.Client.Stylesheets;
using Content.Shared._Onyx.Ghost.Skins;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.Player;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._Onyx.Ghost.Skins.UI;

[GenerateTypedNameReferences]
public sealed partial class GhostSkinsWindow : DefaultWindow
{
    [Dependency] private IPrototypeManager _proto = default!;
    [Dependency] private ISharedPlayerManager _player = default!;
    [Dependency] private IClientPreferencesManager _prefs = default!;
    [Dependency] private IEntityManager _entMan = default!;
    [Dependency] private IEntitySystemManager _entSys = default!;
    private SpriteSystem _sprite = default!;

    private readonly List<SkinRowButton> _rows = new();
    private readonly Dictionary<string, List<SkinRowButton>> _rowsByCategory = new();
    private readonly Dictionary<string, Control> _categoryHeaders = new();
    private readonly SpriteView _preview = new()
    {
        SetSize = new Vector2(128, 128),
        HorizontalAlignment = HAlignment.Center,
        VerticalAlignment = VAlignment.Center,
        Stretch = SpriteView.StretchMode.Fill,
    };

    private EntityUid? _previewEntity;
    private ProtoId<GhostSkinPrototype> _currentSkin;

    public GhostSkinsWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _sprite = _entSys.GetEntitySystem<SpriteSystem>();

        _currentSkin = _prefs.Preferences?.GhostSkin ?? GhostSkinPrototype.DefaultSkinId;

        SearchBox.OnTextChanged += _ => RefreshVisibility();
        ShowAllCheckBox.OnToggled += _ => RefreshVisibility();

        BuildList();
        DetailsContainer.AddChild(_preview);

        OnClose += () =>
        {
            if (_previewEntity is { } old)
                _entMan.TryQueueDeleteEntity(old);
            _previewEntity = null;
        };

        if (_proto.TryIndex(_currentSkin, out var current))
            ShowDetails(current);
        else if (_rows.Count > 0)
            ShowDetails(_rows[0].Skin);

        RefreshSelection();
        RefreshVisibility();
    }

    private void BuildList()
    {
        var session = _player.LocalSession;
        var skins = _proto.EnumeratePrototypes<GhostSkinPrototype>()
            .Where(s => !s.Abstract)
            .OrderBy(s => s.DisplayCategory)
            .ThenBy(s => s.DisplayName);

        foreach (var skin in skins)
        {
            var canSee = false;
            var available = session is not null && skin.CanUse(session, out _, out canSee);
            if (!canSee)
                continue;

            var category = skin.Category;
            if (!_rowsByCategory.TryGetValue(category, out var categoryRows))
            {
                categoryRows = new List<SkinRowButton>();
                _rowsByCategory[category] = categoryRows;

                var header = new BoxContainer
                {
                    Orientation = BoxContainer.LayoutOrientation.Vertical,
                    Margin = new Thickness(2f),
                };
                header.AddChild(new Label
                {
                    Text = skin.DisplayCategory,
                    Margin = new Thickness(2f),
                });
                header.AddChild(new PanelContainer
                {
                    StyleClasses = { StyleClass.LowDivider },
                    MinHeight = 1f,
                    Margin = new Thickness(2f, 2f, 2f, 4f),
                });
                SkinsContainer.AddChild(header);
                _categoryHeaders[category] = header;
            }

            var row = new SkinRowButton(skin, available)
            {
                HorizontalExpand = true,
                ToggleMode = true,
                Text = skin.DisplayName,
                ToolTip = skin.DisplayDesc,
                Margin = new Thickness(2f, 0f),
            };
            if (!available)
                row.ModulateSelfOverride = Color.Gray;

            row.OnToggled += args => OnRowToggled(row, args.Pressed);
            SkinsContainer.AddChild(row);
            _rows.Add(row);
            categoryRows.Add(row);
        }
    }

    private void OnRowToggled(SkinRowButton row, bool pressed)
    {
        ShowDetails(row.Skin);

        if (!row.Available)
        {
            row.Pressed = false;
            return;
        }

        if (!pressed)
        {
            row.Pressed = true;
            return;
        }

        _currentSkin = row.Skin.ID;
        _prefs.SetGhostSkin(_currentSkin);
        RefreshSelection();
    }

    private void RefreshSelection()
    {
        foreach (var row in _rows)
        {
            row.Pressed = row.Available && row.Skin.ID == _currentSkin.Id;
        }
    }

    private void ShowDetails(GhostSkinPrototype skin)
    {
        foreach (var child in DetailsContainer.Children.ToList())
        {
            if (child == _preview)
                continue;

            DetailsContainer.RemoveChild(child);
            child.Dispose();
        }

        if (_previewEntity is { } old)
            _entMan.TryQueueDeleteEntity(old);

        // Preview through the same pipeline as real ghosts:
        // a local observer with the skin component applied.
        var previewEnt = _entMan.Spawn("MobObserver");
        _previewEntity = previewEnt;
        if (skin.Sprite is not null)
        {
            var skinComp = _entMan.EnsureComponent<GhostSkinComponent>(previewEnt);
            skinComp.Skin = skin.ID;
            // EnsureComp fires startup with the default value, so apply explicitly.
            _entSys.GetEntitySystem<GhostSkinSystem>().ApplySkin((previewEnt, skinComp));
        }
        if (_entMan.TryGetComponent<SpriteComponent>(previewEnt, out var sprite))
            _sprite.SetVisible((previewEnt, sprite), true);
        _sprite.ForceUpdate(previewEnt);
        _preview.SetEntity(previewEnt);

        DetailsContainer.AddChild(new Label
        {
            Text = skin.DisplayName,
            StyleClasses = { StyleClass.LabelHeading },
            HorizontalAlignment = HAlignment.Center,
        });

        var canSee = false;
        FormattedMessage? failReason = null;
        var session = _player.LocalSession;
        var available = session is not null && skin.CanUse(session, out failReason, out canSee);

        if (_currentSkin.Id == skin.ID)
        {
            DetailsContainer.AddChild(new Label
            {
                Text = Loc.GetString("ghost-skins-window-selected", ("name", skin.DisplayName)),
                HorizontalAlignment = HAlignment.Center,
            });
        }

        var description = new RichTextLabel
        {
            HorizontalExpand = true,
            Margin = new Thickness(0f, 4f),
        };
        description.SetMessage(skin.DisplayDesc);
        DetailsContainer.AddChild(description);

        if (!available && failReason is not null)
        {
            DetailsContainer.AddChild(new Label
            {
                Text = Loc.GetString("ghost-skins-window-locked"),
                StyleClasses = { StyleClass.LabelHeading },
                HorizontalAlignment = HAlignment.Center,
            });
            DetailsContainer.AddChild(new Label
            {
                Text = Loc.GetString("ghost-skins-window-to-unlock"),
            });
            var reasons = new RichTextLabel
            {
                HorizontalExpand = true,
            };
            reasons.SetMessage(failReason);
            DetailsContainer.AddChild(reasons);
        }
    }

    private void RefreshVisibility()
    {
        var query = SearchBox.Text.Trim();
        var showAll = ShowAllCheckBox.Pressed;
        var anyVisible = false;

        foreach (var row in _rows)
        {
            var matchesSearch = query == string.Empty ||
                row.Skin.DisplayName.Contains(query, StringComparison.OrdinalIgnoreCase);
            row.Visible = matchesSearch && (row.Available || showAll);
            anyVisible |= row.Visible;
        }

        foreach (var (category, header) in _categoryHeaders)
        {
            header.Visible = _rowsByCategory[category].Any(r => r.Visible);
        }

        EmptyLabel.Visible = !anyVisible;
    }

    private sealed partial class SkinRowButton(
        GhostSkinPrototype skin,
        bool available) : Button
    {
        public readonly GhostSkinPrototype Skin = skin;
        public readonly bool Available = available;
    }
}
