using Content.Shared.CartridgeLoader;
using Content.Client.Message;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Onyx.PDA;

[GenerateTypedNameReferences]
public sealed partial class ModernPdaProgramItem : ContainerButton
{
    private readonly StyleBoxFlat _background = CardStyle("#1A2026", "#00000000");
    private readonly StyleBoxFlat _accentBar = CardStyle("#6B9A88", "#00000000");
    private readonly StyleBoxFlat _actionBackground = ActionStyle("#20362D", "#56826E");
    private Color _themeAccent = Color.FromHex("#6B9A88");
    private Entity<CartridgeComponent> _cartridge;
    private string _baseStatus = string.Empty;
    private bool _active;
    private bool _hovered;

    public event Action<EntityUid>? OnProgramItemPressed;
    public event Action<EntityUid>? OnUninstallButtonPressed;
    public event Action<EntityUid>? OnInstallButtonPressed;

    public ModernPdaProgramItem()
    {
        RobustXamlLoader.Load(this);
        Background.PanelOverride = _background;
        AccentBar.PanelOverride = _accentBar;
        InstallButton.StyleBoxOverride = _actionBackground;

        OnPressed += _ => OnProgramItemPressed?.Invoke(_cartridge);
        InstallButton.OnPressed += _ => ToggleInstallation();
        InstallButton.OnMouseEntered += _ => ApplyActionStyle(true);
        InstallButton.OnMouseExited += _ => ApplyActionStyle(false);
        OnMouseEntered += _ =>
        {
            _hovered = true;
            _background.BackgroundColor = Color.FromHex("#20262C");
            RefreshAccentBar();
        };
        OnMouseExited += _ =>
        {
            _hovered = false;
            _background.BackgroundColor = Color.FromHex("#1A2026");
            RefreshAccentBar();
        };
    }

    public ModernPdaProgramItem(Entity<CartridgeComponent> program) : this()
    {
        SetCartridge(program);
    }

    public void SetTheme(Color accent)
    {
        _themeAccent = accent;
        RefreshAccentBar();
    }

    public EntityUid ProgramUid => _cartridge.Owner;

    public void SetActive(bool active)
    {
        _active = active;
        RefreshAccentBar();
        ProgramStatus.Text = active ? $"● {_baseStatus}" : _baseStatus;
    }

    private void RefreshAccentBar()
    {
        _accentBar.BackgroundColor = _active || _hovered ? _themeAccent : ThemeBarColor(_themeAccent);
    }

    public void SetCartridge(Entity<CartridgeComponent> program)
    {
        _cartridge = program;
        var programName = Loc.GetString(program.Comp.ProgramName);
        ProgramName.SetMarkup(programName);
        ToolTip = programName;

        if (program.Comp.Icon is { } icon)
            Icon.SetFromSpriteSpecifier(icon);

        _baseStatus = string.Empty;

        switch (program.Comp.InstallationStatus)
        {
            case InstallationStatus.Cartridge:
                _baseStatus = Loc.GetString("pda-modern-program-cartridge");
                InstallButton.Visible = true;
                InstallButton.Text = Loc.GetString("cartridge-bound-user-interface-install-button");
                ApplyActionStyle(false);
                break;
            case InstallationStatus.Installed:
                _baseStatus = Loc.GetString("pda-modern-program-installed");
                InstallButton.Visible = true;
                InstallButton.Text = Loc.GetString("cartridge-bound-user-interface-uninstall-button");
                ApplyActionStyle(false);
                break;
            case InstallationStatus.Readonly:
                _baseStatus = Loc.GetString("pda-modern-program-system");
                InstallButton.Visible = false;
                break;
        }

        ProgramStatus.Text = _active ? $"● {_baseStatus}" : _baseStatus;
    }

    private void ToggleInstallation()
    {
        if (_cartridge.Comp.InstallationStatus == InstallationStatus.Cartridge)
            OnInstallButtonPressed?.Invoke(_cartridge.Owner);
        else if (_cartridge.Comp.InstallationStatus == InstallationStatus.Installed)
            OnUninstallButtonPressed?.Invoke(_cartridge.Owner);
    }

    private void ApplyActionStyle(bool hovered)
    {
        var uninstall = _cartridge.Comp.InstallationStatus == InstallationStatus.Installed;
        _actionBackground.BackgroundColor = Color.FromHex(uninstall
            ? hovered ? "#5A3035" : "#3B2529"
            : hovered ? "#315443" : "#20362D");
        _actionBackground.BorderColor = Color.FromHex(uninstall ? "#A85B65" : "#56826E");
        InstallButton.Label.FontColorOverride = Color.FromHex(uninstall ? "#F0B0B5" : "#B8E3CF");
    }

    private static StyleBoxFlat CardStyle(string background, string border)
    {
        return new StyleBoxFlat
        {
            BackgroundColor = Color.FromHex(background),
            BorderColor = Color.FromHex(border),
            BorderThickness = new Thickness(1),
        };
    }

    private static StyleBoxFlat ActionStyle(string background, string border)
    {
        return new StyleBoxFlat
        {
            BackgroundColor = Color.FromHex(background),
            BorderColor = Color.FromHex(border),
            BorderThickness = new Thickness(1),
            ContentMarginLeftOverride = 10,
            ContentMarginRightOverride = 10,
            ContentMarginTopOverride = 3,
            ContentMarginBottomOverride = 3,
        };
    }

    private static Color ThemeBarColor(Color accent)
    {
        accent.A = 0.45f;
        return accent;
    }
}
