using Content.Client.GameTicking.Managers;
using Content.Client.Message;
using Content.Client.PDA;
using Content.Shared.AlertLevel;
using Content.Shared.CartridgeLoader;
using Content.Shared.PDA;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._Onyx.PDA;

[GenerateTypedNameReferences]
public sealed partial class ModernPdaMenu : PdaWindow
{
    [Dependency] private IClipboardManager _clipboard = null!;
    [Dependency] private IGameTiming _gameTiming = null!;
    [Dependency] private IEntitySystemManager _entitySystem = null!;

    private readonly AlertLevelSystem _alert;
    private readonly ClientGameTicker _gameTicker;

    private const int HomeView = 0;
    private const int ProgramListView = 1;
    private const int SettingsView = 2;
    private const int ProgramContentView = 3;

    private string _pdaOwner = Loc.GetString("comp-pda-ui-unknown");
    private string _owner = Loc.GetString("comp-pda-ui-unknown");
    private string _jobTitle = Loc.GetString("comp-pda-ui-unassigned");
    private string _stationName = Loc.GetString("comp-pda-ui-unknown");
    private string _alertLevel = Loc.GetString("comp-pda-ui-unknown");
    private string _instructions = Loc.GetString("comp-pda-ui-unknown");
    private int _currentView;
    private Color _themeAccent = Color.FromHex("#6B9A88");
    private bool _applyingTheme;

    private static readonly (string LocKey, Color Color)[] ThemePresets =
    [
        ("pda-modern-theme-civilian", Color.FromHex("#6B9A88")),
        ("pda-modern-theme-engineering", Color.FromHex("#D0A93D")),
        ("pda-modern-theme-medical", Color.FromHex("#4F9AB5")),
        ("pda-modern-theme-science", Color.FromHex("#9B62C7")),
        ("pda-modern-theme-security", Color.FromHex("#B54B45")),
        ("pda-modern-theme-cargo", Color.FromHex("#C58B52")),
        ("pda-modern-theme-command", Color.FromHex("#4E82B5")),
    ];

    public event Action<EntityUid>? OnProgramItemPressed;
    public event Action<EntityUid>? OnUninstallButtonPressed;
    public event Action<EntityUid>? OnInstallButtonPressed;
    public event Action<Color?>? OnThemeChanged; // <Onyx-PdaTheme>

    public ModernPdaMenu()
    {
        IoCManager.InjectDependencies(this);
        _alert = _entitySystem.GetEntitySystem<AlertLevelSystem>();
        _gameTicker = _entitySystem.GetEntitySystem<ClientGameTicker>();
        RobustXamlLoader.Load(this);

        ViewContainer.OnChildAdded += control => control.Visible = false;

        HomeButton.IconTexture = new SpriteSpecifier.Texture(new("/Textures/Interface/home.png"));
        FlashLightToggleButton.IconTexture = new SpriteSpecifier.Texture(new("/Textures/Interface/light.png"));
        EjectPenButton.IconTexture = new SpriteSpecifier.Texture(new("/Textures/Interface/pencil.png"));
        EjectIdButton.IconTexture = new SpriteSpecifier.Texture(new("/Textures/Interface/eject.png"));
        EjectPaiButton.IconTexture = new SpriteSpecifier.Texture(new("/Textures/Interface/pai.png"));
        PowerOffButton.IconTexture = new SpriteSpecifier.Texture(new("/Textures/_Onyx/Interface/pda_power.png"));
        ProgramCloseButton.IconTexture = new SpriteSpecifier.Texture(new("/Textures/Interface/Nano/cross.svg.png"));

        RefreshNavigationButton(FlashLightToggleButton);
        RefreshNavigationButton(EjectPenButton);
        RefreshNavigationButton(EjectIdButton);
        RefreshNavigationButton(EjectPaiButton);
        RefreshNavigationButton(PowerOffButton);

        HomeButton.OnPressed += _ => ToHomeScreen();
        ProgramListButton.OnPressed += _ => SelectView(ProgramListView, ProgramListButton);
        SettingsButton.OnPressed += _ => SelectView(SettingsView, SettingsButton);
        ProgramTitle.OnPressed += _ => SelectView(ProgramContentView, ProgramTitle);
        ProgramCloseButton.OnPressed += _ =>
        {
            HideProgramHeader();
            ToHomeScreen();
        };

        PdaOwnerButton.OnPressed += _ => _clipboard.SetText(_pdaOwner);
        IdInfoButton.OnPressed += _ => _clipboard.SetText(_owner + ", " + _jobTitle);
        StationNameButton.OnPressed += _ => _clipboard.SetText(_stationName);
        StationAlertLevelButton.OnPressed += _ => _clipboard.SetText(_alertLevel);
        StationTimeButton.OnPressed += _ => _clipboard.SetText(GetStationTime());
        StationAlertLevelInstructionsButton.OnPressed += _ => _clipboard.SetText(_instructions);

        foreach (var (locKey, _) in ThemePresets)
            ThemePreset.AddItem(Loc.GetString(locKey));

        ThemePreset.OnItemSelected += args =>
        {
            ThemePreset.SelectId(args.Id);
            SetTheme(ThemePresets[args.Id].Color);
        };
        ThemePicker.OnColorChanged += accent => SetTheme(accent, true, false);
        ThemeResetButton.OnPressed += _ =>
        {
            OnThemeChanged?.Invoke(null);
        };

        HideAllViews();
        ToHomeScreen();
        SetTheme(_themeAccent, false);
    }

    public void UpdateState(PdaUpdateState state)
    {
        SetTheme(state.ThemeAccent, false); // <Onyx-PdaTheme>
        FlashLightToggleButton.IsActive = state.FlashlightEnabled;

        if (state.PdaOwnerInfo.ActualOwnerName != null)
        {
            _pdaOwner = state.PdaOwnerInfo.ActualOwnerName;
            PdaOwnerLabel.SetMarkup(Loc.GetString("comp-pda-ui-owner", ("actualOwnerName", _pdaOwner)));
            PdaOwnerLabel.Visible = true;
        }
        else
        {
            PdaOwnerLabel.Visible = false;
        }

        if (state.PdaOwnerInfo.IdOwner != null || state.PdaOwnerInfo.JobTitle != null)
        {
            _owner = state.PdaOwnerInfo.IdOwner ?? Loc.GetString("comp-pda-ui-unknown");
            _jobTitle = state.PdaOwnerInfo.JobTitle ?? Loc.GetString("comp-pda-ui-unassigned");
            IdInfoLabel.SetMarkup(Loc.GetString("comp-pda-ui", ("owner", _owner), ("jobTitle", _jobTitle)));
        }
        else
        {
            IdInfoLabel.SetMarkup(Loc.GetString("comp-pda-ui-blank"));
        }

        var hasMiningPoints = state.PdaOwnerInfo.MiningPoints > 0;
        var hasBitrunningPoints = state.PdaOwnerInfo.BitrunningPoints > 0;
        MiningPointsLabel.Visible = hasMiningPoints || hasBitrunningPoints;
        if (hasMiningPoints && hasBitrunningPoints)
        {
            MiningPointsLabel.SetMarkup(Loc.GetString("comp-pda-ui-points",
                ("miningPoints", state.PdaOwnerInfo.MiningPoints),
                ("bitrunningPoints", state.PdaOwnerInfo.BitrunningPoints)));
        }
        else if (hasMiningPoints)
        {
            MiningPointsLabel.SetMarkup(Loc.GetString("comp-pda-ui-mining-points",
                ("points", state.PdaOwnerInfo.MiningPoints)));
        }
        else if (hasBitrunningPoints)
        {
            MiningPointsLabel.SetMarkup(Loc.GetString("comp-pda-ui-bitrunning-points",
                ("points", state.PdaOwnerInfo.BitrunningPoints)));
        }

        _stationName = state.StationName ?? Loc.GetString("comp-pda-ui-unknown");
        StationNameLabel.SetMarkup(Loc.GetString("comp-pda-ui-station", ("station", _stationName)));
        UpdateStationTime();

        var alertColor = state.PdaOwnerInfo.StationAlertColor;
        (_alertLevel, _, _instructions) = _alert.AlertLevelData(state.PdaOwnerInfo.StationAlertLevel);
        StationAlertLevelLabel.SetMarkup(Loc.GetString("comp-pda-ui-station-alert-level",
            ("color", alertColor), ("level", _alertLevel)));
        StationAlertLevelInstructions.SetMarkup(Loc.GetString("comp-pda-ui-station-alert-level-instructions",
            ("instructions", _instructions)));

        var address = string.IsNullOrWhiteSpace(state.Address) ? "-" : state.Address.ToUpperInvariant();
        AddressLabel.Text = address;
        EjectIdButton.IsActive = state.PdaOwnerInfo.IdOwner != null || state.PdaOwnerInfo.JobTitle != null;
        EjectPenButton.IsActive = state.HasPen;
        EjectPaiButton.IsActive = state.HasPai;
        ActivateMusicButton.Visible = state.CanPlayMusic;
        ShowUplinkButton.Visible = state.HasUplink;
        LockUplinkButton.Visible = state.HasUplink;
    }

    public void UpdateAvailablePrograms(List<(EntityUid, CartridgeComponent)> programs)
    {
        if (programs.Count == 0)
        {
            ProgramList.RemoveAllChildren();
            ProgramList.AddChild(new Label
            {
                Text = Loc.GetString("comp-pda-io-no-programs-available"),
                HorizontalAlignment = HAlignment.Center,
                VerticalAlignment = VAlignment.Center,
                VerticalExpand = true,
            });
            return;
        }

        if (ProgramList.ChildCount > 0 && ProgramList.Children[0] is Label label)
            label.Orphan();

        while (ProgramList.ChildCount > programs.Count)
            ProgramList.Children[ProgramList.ChildCount - 1].Orphan();

        for (var i = 0; i < programs.Count; i++)
        {
            var cartridge = programs[i];
            if (i < ProgramList.ChildCount)
            {
                var currentItem = ProgramList.Children[i];
                if (currentItem is ModernPdaProgramItem programItem)
                {
                    programItem.SetCartridge(cartridge);
                    continue;
                }

                DebugTools.Assert(i == ProgramList.ChildCount - 1);
                currentItem.Orphan();
            }

            var item = new ModernPdaProgramItem(cartridge);
            item.SetTheme(_themeAccent);
            item.OnProgramItemPressed += uid => OnProgramItemPressed?.Invoke(uid);
            item.OnUninstallButtonPressed += uid => OnUninstallButtonPressed?.Invoke(uid);
            item.OnInstallButtonPressed += uid => OnInstallButtonPressed?.Invoke(uid);
            ProgramList.AddChild(item);
        }
    }

    public void ToHomeScreen()
    {
        SelectView(HomeView, HomeButton);
    }

    public void HideProgramHeader()
    {
        ProgramTitle.IsCurrent = false;
        ProgramTitle.Visible = false;
        ProgramCloseButton.Visible = false;
        ProgramListButton.Visible = true;
        SettingsButton.Visible = true;
        NavigationFill.Visible = true;
    }

    public void ToProgramView(string title)
    {
        ProgramTitle.Visible = true;
        ProgramCloseButton.Visible = true;
        ProgramListButton.Visible = false;
        SettingsButton.Visible = false;
        NavigationFill.Visible = false;
        ProgramTitle.LabelText = title;
        SelectView(ProgramContentView, ProgramTitle);
    }

    private void SelectView(int view, PdaNavigationButton selected)
    {
        HomeButton.IsCurrent = selected == HomeButton;
        ProgramListButton.IsCurrent = selected == ProgramListButton;
        SettingsButton.IsCurrent = selected == SettingsButton;
        ProgramTitle.IsCurrent = selected == ProgramTitle;
        ChangeView(view);
    }

    private void SetTheme(Color accent, bool notify = true, bool syncPicker = true)
    {
        if (_applyingTheme)
            return;

        _applyingTheme = true;
        var changed = accent != _themeAccent;
        _themeAccent = accent;
        if (notify)
            OnThemeChanged?.Invoke(accent);
        if (syncPicker && changed)
            ThemePicker.Color = accent;
        ThemeColorPreview.PanelOverride = new StyleBoxFlat { BackgroundColor = accent };

        var border = Color.FromHex(accent.ToHex());
        ((StyleBoxFlat) IdentityPanel.PanelOverride!).BorderColor = border;
        IdentityHeaderLabel.FontColorOverride = accent;
        ((StyleBoxFlat) StationPanel.PanelOverride!).BorderColor = border;
        ((StyleBoxFlat) TimePanel.PanelOverride!).BorderColor = border;
        ((StyleBoxFlat) AlertPanel.PanelOverride!).BorderColor = border;
        ((StyleBoxFlat) ThemePanel.PanelOverride!).BorderColor = border;
        AlertHeaderLabel.FontColorOverride = accent;

        HomeButton.ActiveFgColor = accent.ToHex();
        ProgramListButton.ActiveFgColor = accent.ToHex();
        SettingsButton.ActiveFgColor = accent.ToHex();
        ProgramCloseButton.InactiveBgColor = accent.ToHex();
        ProgramCloseButton.InactiveFgColor = "#FFFFFF";
        RefreshNavigationButton(HomeButton);
        RefreshNavigationButton(ProgramListButton);
        RefreshNavigationButton(SettingsButton);
        RefreshNavigationButton(ProgramTitle);
        HomeButton.IsActive = true;
        ProgramListButton.IsActive = true;
        SettingsButton.IsActive = true;
        RefreshNavigationButton(ProgramCloseButton);
        ProgramCloseButton.IsActive = false;

        foreach (var child in ProgramList.Children)
        {
            if (child is ModernPdaProgramItem program)
                program.SetTheme(accent);
        }

        foreach (var child in Settings.Children)
        {
            if (child is ModernPdaSettingsButton setting)
                setting.SetTheme(accent);
        }

        _applyingTheme = false;
    }

    private static void RefreshNavigationButton(PdaNavigationButton button)
    {
        var current = button.IsCurrent;
        button.IsCurrent = false;
        button.IsCurrent = current;
    }

    private void ChangeView(int view)
    {
        if (ViewContainer.ChildCount <= view)
            return;

        ViewContainer.GetChild(_currentView).Visible = false;
        ViewContainer.GetChild(view).Visible = true;
        _currentView = view;
    }

    private void HideAllViews()
    {
        foreach (var view in ViewContainer.Children)
            view.Visible = false;
    }

    private string GetStationTime()
    {
        return _gameTiming.CurTime.Subtract(_gameTicker.RoundStartTimeSpan).ToString("hh\\:mm\\:ss");
    }

    private void UpdateStationTime()
    {
        var time = GetStationTime();
        StationTimeLabel.SetMarkup(Loc.GetString("comp-pda-ui-station-time", ("time", time)));
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        base.Draw(handle);
        UpdateStationTime();
    }
}
