using System.Linq;
using Content.Client.GameTicking;
using Content.Client.Message;
using Content.Client.PDA;
using Content.Shared.AlertLevel;
using Content.Shared.CartridgeLoader;
using Content.Shared.PDA;
using Content.Shared._Onyx.Time;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._Onyx.PDA;

[GenerateTypedNameReferences]
public sealed partial class ModernPdaMenu : PdaWindow
{
    [Dependency] private IClipboardManager _clipboard = null!;
    [Dependency] private IGameTiming _gameTiming = null!;
    [Dependency] private IEntitySystemManager _entitySystem = null!;
    [Dependency] private IConfigurationManager _config = null!;

    private readonly AlertLevelSystem _alert;
    private readonly ClientGameTicker _gameTicker;

    private const int HomeView = 0;
    private const int ProgramListView = 1;
    private const int SettingsView = 2;
    private const int ProgramContentView = 3;

    private string _pdaOwner = Loc.GetString("comp-pda-ui-unknown");
    private string _owner = Loc.GetString("comp-pda-ui-unknown");
    private string _jobTitle = Loc.GetString("comp-pda-ui-unassigned");
    private string _stationName = Loc.GetString("comp-pda-ui-unknown");
    private string _alertLevel = Loc.GetString("comp-pda-ui-unknown");
    private string _instructions = Loc.GetString("comp-pda-ui-unknown");
    private string _address = "-";
    private int _currentView;
    private Color _themeAccent = Color.FromHex("#6B9A88");
    private bool _applyingTheme;
    private float _lastBatteryCharge;
    private float _lastBatteryMax;
    private float _lastBatteryLowThreshold = 0.25f;
    private int _diskUsed;
    private int _diskMax;
    private EntityUid? _activeProgram;
    private bool _themeApplied;
    private TimeSpan _nextClockUpdate;

    private List<(LocId LocKey, Color Color)> _themes = new();

    public event Action<EntityUid>? OnProgramItemPressed;
    public event Action<EntityUid>? OnUninstallButtonPressed;
    public event Action<EntityUid>? OnInstallButtonPressed;
    public event Action<Color?>? OnThemeChanged; // <Onyx-PdaTheme>

    public ModernPdaMenu()
    {
        IoCManager.InjectDependencies(this);
        _alert = _entitySystem.GetEntitySystem<AlertLevelSystem>();
        _gameTicker = _entitySystem.GetEntitySystem<ClientGameTicker>();
        RobustXamlLoader.Load(this);

        ViewContainer.OnChildAdded += control => control.Visible = false;

        HomeButton.IconTexture = new SpriteSpecifier.Texture(new("/Textures/Interface/home.png"));
        ProgramListButton.ButtonText = Loc.GetString("comp-pda-io-program-list-button");
        SettingsButton.ButtonText = Loc.GetString("comp-pda-io-settings-button");
        FlashLightToggleButton.IconTexture = new SpriteSpecifier.Texture(new("/Textures/Interface/light.png"));
        EjectPenButton.IconTexture = new SpriteSpecifier.Texture(new("/Textures/Interface/pencil.png"));
        EjectIdButton.IconTexture = new SpriteSpecifier.Texture(new("/Textures/Interface/eject.png"));
        EjectPaiButton.IconTexture = new SpriteSpecifier.Texture(new("/Textures/Interface/pai.png"));
        PowerOffButton.IconTexture = new SpriteSpecifier.Texture(new("/Textures/_Onyx/Interface/pda_power.png"));
        ProgramCloseButton.IconTexture = new SpriteSpecifier.Texture(new("/Textures/Interface/Nano/cross.svg.png"));

        HomeButton.OnPressed += _ => ToHomeScreen();
        ProgramListButton.OnPressed += _ => SelectView(ProgramListView, ProgramListButton);
        SettingsButton.OnPressed += _ => SelectView(SettingsView, SettingsButton);
        ProgramTitle.OnPressed += _ => SelectView(ProgramContentView, ProgramTitle);
        ProgramCloseButton.OnPressed += _ =>
        {
            HideProgramHeader();
            ToHomeScreen();
        };

        PdaOwnerButton.OnPressed += _ => _clipboard.SetText(_pdaOwner);
        IdInfoButton.OnPressed += _ => _clipboard.SetText(_owner + ", " + _jobTitle);
        StationNameButton.OnPressed += _ => _clipboard.SetText(_stationName);
        StationAlertLevelButton.OnPressed += _ => _clipboard.SetText(_alertLevel);
        StatusTimeButton.OnPressed += _ => _clipboard.SetText(GetStationTime());
        StationAlertLevelInstructionsButton.OnPressed += _ => _clipboard.SetText(_instructions);
        AddressCopyButton.OnPressed += _ => _clipboard.SetText(_address);

        ThemePreset.OnItemSelected += args =>
        {
            ThemePreset.SelectId(args.Id);
            SetTheme(_themes[args.Id].Color);
        };
        ThemePicker.OnColorChanged += accent => SetTheme(accent, true, false);
        ThemeResetButton.OnPressed += _ =>
        {
            OnThemeChanged?.Invoke(null);
        };

        HideAllViews();
        ToHomeScreen();
        SetTheme(_themeAccent, false);
    }

    public void UpdateState(PdaUpdateState state)
    {
        SetTheme(state.ThemeAccent, false); // <Onyx-PdaTheme>
        UpdateBattery(state.BatteryCharge, state.BatteryMax, state.BatteryLowThreshold);
        _diskUsed = state.DiskUsed;
        _diskMax = state.DiskMax;
        UpdateResources();
        FlashLightToggleButton.IsActive = state.FlashlightEnabled;
        FlashLightToggleButton.Pressed = state.FlashlightEnabled;

        if (state.PdaOwnerInfo.ActualOwnerName != null)
        {
            _pdaOwner = state.PdaOwnerInfo.ActualOwnerName;
            PdaOwnerLabel.SetMarkup(Loc.GetString("comp-pda-ui-owner", ("actualOwnerName", _pdaOwner)));
            PdaOwnerLabel.Visible = true;
        }
        else
        {
            PdaOwnerLabel.Visible = false;
        }

        if (state.PdaOwnerInfo.IdOwner != null || state.PdaOwnerInfo.JobTitle != null)
        {
            _owner = state.PdaOwnerInfo.IdOwner ?? Loc.GetString("comp-pda-ui-unknown");
            _jobTitle = state.PdaOwnerInfo.JobTitle ?? Loc.GetString("comp-pda-ui-unassigned");
            IdInfoLabel.SetMarkup(Loc.GetString("comp-pda-ui", ("owner", _owner), ("jobTitle", _jobTitle)));
        }
        else
        {
            IdInfoLabel.SetMarkup(Loc.GetString("comp-pda-ui-blank"));
        }

        var hasMiningPoints = state.PdaOwnerInfo.MiningPoints > 0;
        var hasBitrunningPoints = state.PdaOwnerInfo.BitrunningPoints > 0;
        MiningPointsLabel.Visible = hasMiningPoints || hasBitrunningPoints;
        if (hasMiningPoints && hasBitrunningPoints)
        {
            MiningPointsLabel.SetMarkup(Loc.GetString("comp-pda-ui-points",
                ("miningPoints", state.PdaOwnerInfo.MiningPoints),
                ("bitrunningPoints", state.PdaOwnerInfo.BitrunningPoints)));
        }
        else if (hasMiningPoints)
        {
            MiningPointsLabel.SetMarkup(Loc.GetString("comp-pda-ui-mining-points",
                ("points", state.PdaOwnerInfo.MiningPoints)));
        }
        else if (hasBitrunningPoints)
        {
            MiningPointsLabel.SetMarkup(Loc.GetString("comp-pda-ui-bitrunning-points",
                ("points", state.PdaOwnerInfo.BitrunningPoints)));
        }

        _stationName = state.StationName ?? Loc.GetString("comp-pda-ui-unknown");
        StationNameLabel.SetMarkup(Loc.GetString("comp-pda-ui-station", ("station", _stationName)));
        UpdateStationTime();

        var alertColor = state.PdaOwnerInfo.StationAlertColor;
        (_alertLevel, _, _instructions) = _alert.AlertLevelData(state.PdaOwnerInfo.StationAlertLevel);
        StationAlertLevelLabel.SetMarkup(Loc.GetString("comp-pda-ui-station-alert-level",
            ("color", alertColor), ("level", _alertLevel)));
        StationAlertLevelInstructions.SetMarkup(Loc.GetString("comp-pda-ui-station-alert-level-instructions",
            ("instructions", _instructions)));

        _address = string.IsNullOrWhiteSpace(state.Address) ? "-" : state.Address.ToUpperInvariant();
        AddressLabel.Text = _address;
        EjectIdButton.IsActive = state.PdaOwnerInfo.IdOwner != null || state.PdaOwnerInfo.JobTitle != null;
        EjectPenButton.IsActive = state.HasPen;
        EjectPaiButton.IsActive = state.HasPai;
        PaiStateLabel.Text = Loc.GetString(state.HasPai
            ? "pda-modern-pai-present"
            : "pda-modern-pai-absent");
        ActivateMusicButton.Visible = state.CanPlayMusic;
        ShowUplinkButton.Visible = state.HasUplink;
        LockUplinkButton.Visible = state.HasUplink;
    }

    public void UpdateAvailablePrograms(List<(EntityUid, CartridgeComponent)> programs)
    {
        if (programs.Count == 0)
        {
            ProgramList.RemoveAllChildren();
            ProgramList.AddChild(new Label
            {
                Text = Loc.GetString("comp-pda-io-no-programs-available"),
                HorizontalAlignment = HAlignment.Center,
                VerticalAlignment = VAlignment.Center,
                VerticalExpand = true,
            });
        }
        else
        {
            if (ProgramList.ChildCount > 0 && ProgramList.Children[0] is Label label)
                label.Orphan();

            while (ProgramList.ChildCount > programs.Count)
                ProgramList.Children[ProgramList.ChildCount - 1].Orphan();

            for (var i = 0; i < programs.Count; i++)
            {
                var cartridge = programs[i];
                if (i < ProgramList.ChildCount)
                {
                    var currentItem = ProgramList.Children[i];
                    if (currentItem is ModernPdaProgramItem programItem)
                    {
                        programItem.SetCartridge(cartridge);
                        programItem.SetActive(_activeProgram == cartridge.Item1);
                        continue;
                    }

                    DebugTools.Assert(i == ProgramList.ChildCount - 1);
                    currentItem.Orphan();
                }

                var item = new ModernPdaProgramItem(cartridge);
                item.SetTheme(_themeAccent);
                item.SetActive(_activeProgram == cartridge.Item1);
                item.OnProgramItemPressed += uid => OnProgramItemPressed?.Invoke(uid);
                item.OnUninstallButtonPressed += uid => OnUninstallButtonPressed?.Invoke(uid);
                item.OnInstallButtonPressed += uid => OnInstallButtonPressed?.Invoke(uid);
                ProgramList.AddChild(item);
            }
        }

        var hasCartridge = programs.Any(p => p.Item2.InstallationStatus == InstallationStatus.Cartridge);
        CartridgeStateLabel.Text = Loc.GetString(hasCartridge
            ? "pda-modern-cartridge-present"
            : "pda-modern-cartridge-absent");

        UpdateResources();
    }

    public void SetActiveProgram(EntityUid? uid)
    {
        _activeProgram = uid;

        foreach (var child in ProgramList.Children)
        {
            if (child is ModernPdaProgramItem program)
                program.SetActive(uid != null && program.ProgramUid == uid);
        }
    }

    private void UpdateResources()
    {
        DiskBar.Value = _diskMax > 0 ? Math.Clamp((float) _diskUsed / _diskMax, 0f, 1f) : 0f;
        DiskLabel.Text = Loc.GetString("pda-modern-disk-value", ("used", _diskUsed), ("max", _diskMax));
    }

    public void ToHomeScreen()
    {
        SelectView(HomeView, HomeButton);
    }

    public void SetSidebarBrand(string? brand)
    {
        SidebarBrandLabel.Visible = !string.IsNullOrEmpty(brand);
        if (!string.IsNullOrEmpty(brand))
            SidebarBrandLabel.Text = brand;
    }

    public void SetupThemes(List<(LocId LocKey, Color Color)> themes)
    {
        _themes = themes;
        ThemePreset.Clear();

        if (_themes.Count == 0)
        {
            ThemePanel.Visible = false;
            return;
        }

        foreach (var (locKey, _) in _themes)
            ThemePreset.AddItem(Loc.GetString(locKey));

        var selected = 0;
        for (var i = 0; i < _themes.Count; i++)
        {
            if (_themes[i].Color == _themeAccent)
            {
                selected = i;
                break;
            }
        }
        ThemePreset.SelectId(selected);

        var locked = _themes.Count == 1;
        ThemePreset.Disabled = locked;
        ThemePicker.MouseFilter = locked ? MouseFilterMode.Ignore : MouseFilterMode.Stop;
        ThemeResetButton.Disabled = locked;

        if (locked)
            SetTheme(_themes[0].Color, false);
    }

    public void HideProgramHeader()
    {
        ProgramTitle.IsCurrent = false;
        ProgramTitle.Visible = false;
        ProgramCloseButton.Visible = false;
        ProgramListButton.Visible = true;
        SettingsButton.Visible = true;
    }

    public void ToProgramView(string title)
    {
        ProgramTitle.Visible = true;
        ProgramCloseButton.Visible = true;
        ProgramListButton.Visible = false;
        SettingsButton.Visible = false;
        ProgramTitle.LabelText = title;
        SelectView(ProgramContentView, ProgramTitle);
    }

    private void SelectView(int view, Control selected)
    {
        HomeButton.IsCurrent = selected == HomeButton;
        ProgramListButton.IsCurrent = selected == ProgramListButton;
        SettingsButton.IsCurrent = selected == SettingsButton;
        ProgramTitle.IsCurrent = selected == ProgramTitle;
        ChangeView(view);
    }

    public void UpdateBatteryLevel(float charge, float max)
    {
        UpdateBattery(charge, max, _lastBatteryLowThreshold);
    }

    private void UpdateBattery(float charge, float max, float lowThreshold)
    {
        _lastBatteryCharge = charge;
        _lastBatteryMax = max;
        _lastBatteryLowThreshold = lowThreshold;

        var level = max > 0f ? Math.Clamp(charge / max, 0f, 1f) : 0f;
        var low = max <= 0f || level <= lowThreshold;
        var color = low ? Color.FromHex("#E48787") : _themeAccent;

        BatteryLabel.Text = max <= 0f
            ? Loc.GetString("pda-modern-battery-no-cell")
            : $"{level * 100f:F0}%";
        BatteryLabel.FontColorOverride = color;

        BatteryBar.Value = level;
        if (BatteryBar.ForegroundStyleBoxOverride is StyleBoxFlat box)
            box.BackgroundColor = color;

        BatteryLowBadge.Visible = max > 0f && level <= lowThreshold;
    }

    private void SetTheme(Color accent, bool notify = true, bool syncPicker = true)
    {
        if (_applyingTheme)
            return;

        if (_themeApplied && !notify && accent == _themeAccent)
            return;

        _themeApplied = true;
        _applyingTheme = true;
        var changed = accent != _themeAccent;
        _themeAccent = accent;
        if (notify)
            OnThemeChanged?.Invoke(accent);
        if (syncPicker && changed)
            ThemePicker.Color = accent;
        ThemeColorPreview.PanelOverride = new StyleBoxFlat { BackgroundColor = accent };

        PanelContainer[] cards =
        [
            UserCard, DeviceCard, StationCard, ThemePanel,
        ];
        foreach (var card in cards)
        {
            if (card.PanelOverride is StyleBoxFlat box)
                box.BorderColor = accent;
        }

        Label[] headers =
        [
            UserHeaderLabel, DeviceHeaderLabel, StationHeaderLabel,
        ];
        foreach (var header in headers)
            header.FontColorOverride = accent;

        HomeButton.AccentColor = accent;
        ProgramListButton.AccentColor = accent;
        SettingsButton.AccentColor = accent;
        if (DiskBar.ForegroundStyleBoxOverride is StyleBoxFlat diskBox)
            diskBox.BackgroundColor = accent;
        ProgramCloseButton.InactiveBgColor = accent.ToHex();
        ProgramCloseButton.InactiveFgColor = "#FFFFFF";
        ProgramCloseButton.IsActive = false;

        foreach (var child in ProgramList.Children)
        {
            if (child is ModernPdaProgramItem program)
                program.SetTheme(accent);
        }

        foreach (var child in Settings.Children)
        {
            if (child is ModernPdaSettingsButton setting)
                setting.SetTheme(accent);
        }

        UpdateBattery(_lastBatteryCharge, _lastBatteryMax, _lastBatteryLowThreshold);
        _applyingTheme = false;
    }

    private void ChangeView(int view)
    {
        if (ViewContainer.ChildCount <= view)
            return;

        ViewContainer.GetChild(_currentView).Visible = false;
        ViewContainer.GetChild(view).Visible = true;
        _currentView = view;
    }

    private void HideAllViews()
    {
        foreach (var view in ViewContainer.Children)
            view.Visible = false;
    }

    private string GetStationTime()
    {
        var time = _gameTiming.CurTime.Subtract(_gameTicker.RoundStartTimeSpan).ToString("hh\\:mm\\:ss");
        var date = InGameDate.Now(_config).ToString("dd.MM.yyyy");
        return $"{time} | {date}";
    }

    private void UpdateStationTime()
    {
        StatusTimeLabel.Text = GetStationTime();
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        base.Draw(handle);

        if (_gameTiming.CurTime < _nextClockUpdate)
            return;

        _nextClockUpdate = _gameTiming.CurTime + TimeSpan.FromSeconds(1);
        UpdateStationTime();
    }
}
