using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Content.Shared._Onyx.Medical.Surgery;

namespace Content.Client._Onyx.Medical.Surgery;

[GenerateTypedNameReferences]
public sealed partial class SurgeryStepButton : SurgeryChoiceControl
{
    public EntProtoId StepId { get; set; }

    public SurgeryStepButton()
    {
        RobustXamlLoader.Load(this);
    }
}
