// Content taken from Wega (https://github.com/wega-team/ss14-wega), licensed under GNU GPL v3.
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared.DetailExaminable;
using Content.Shared.Humanoid;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Onyx.DetailExaminable;

[GenerateTypedNameReferences]
public sealed partial class DetailExaminableWindow : FancyWindow
{
    public DetailExaminableWindow()
    {
        RobustXamlLoader.Load(this);
        PreviewTabs.SetTabTitle(0, Loc.GetString("flavor-tab-flavor"));
        PreviewTabs.SetTabTitle(1, Loc.GetString("flavor-tab-character"));
    }

    public void SetEntity(EntityUid target, DetailExaminableComponent detail, HumanoidProfileComponent humanoid)
    {
        var entManager = IoCManager.Resolve<IEntityManager>();
        PreviewNameText.Text = entManager.GetComponent<MetaDataComponent>(target).EntityName;
        var speciesId = humanoid.Species;
        var sexValue = humanoid.Sex;
        var genderValue = humanoid.Gender;
        var species = Loc.GetString($"species-name-{speciesId.ToString().ToLowerInvariant()}");
        var sex = Loc.GetString($"humanoid-profile-editor-sex-{sexValue.ToString().ToLowerInvariant()}-text");
        var gender = Loc.GetString($"humanoid-profile-editor-pronouns-{genderValue.ToString().ToLowerInvariant()}-text");
        PreviewGenderText.Text = $"{species}|{sex}|{gender}";
        TargetPreview.SetEntity(target);

        PreviewAppearanceText.SetMessage(GetContent(detail.Content, "detail-examinable-empty-flavor"));
        PreviewTraitsText.SetMessage(GetContent(detail.CharacterContent, "detail-examinable-empty-character"));
        PreviewOOCText.SetMessage(GetContent(detail.OOCContent, "detail-examinable-empty-ooc"));
        PreviewTagsText.Text = detail.TagsContent;
        SetLinks(detail.LinksContent);
    }

    private static string GetContent(string content, string emptyMessage)
    {
        return string.IsNullOrWhiteSpace(content) ? Loc.GetString(emptyMessage) : content;
    }

    private void SetLinks(string linksText)
    {
        PreviewLinksContainer.RemoveAllChildren();
        if (string.IsNullOrWhiteSpace(linksText))
        {
            PreviewLinksContainer.AddChild(new Label
            {
                Text = Loc.GetString("detail-examinable-empty-links"),
                HorizontalExpand = true,
                HorizontalAlignment = HAlignment.Center,
                FontColorOverride = Color.Gray,
            });
            return;
        }

        foreach (var link in linksText.Split([',', ' ', '\n', '\r', '\t'], StringSplitOptions.RemoveEmptyEntries))
        {
            if (!link.StartsWith("http://", StringComparison.OrdinalIgnoreCase) &&
                !link.StartsWith("https://", StringComparison.OrdinalIgnoreCase) &&
                !link.StartsWith("www.", StringComparison.OrdinalIgnoreCase))
            {
                PreviewLinksContainer.AddChild(new Label
                {
                    Text = link,
                    HorizontalAlignment = HAlignment.Center,
                    FontColorOverride = Color.Gray,
                });
                continue;
            }

            var url = link.StartsWith("www.", StringComparison.OrdinalIgnoreCase) ? $"https://{link}" : link;
            var button = new Button
            {
                Text = link.Length > 40 ? $"{link[..37]}..." : link,
                ToolTip = Loc.GetString("humanoid-profile-editor-link-tooltip", ("url", link)),
                HorizontalExpand = true,
                HorizontalAlignment = HAlignment.Center,
                StyleClasses = { StyleClass.ButtonOpenBoth },
            };
            button.OnPressed += _ => IoCManager.Resolve<IUriOpener>().OpenUri(url);
            PreviewLinksContainer.AddChild(button);
        }
    }
}
