// Space Onyx
// Copyright (C) 2026 Space Onyx contributors
//
// This file is licensed under AGPL-3.0-or-later.
// See LICENSES for the full license text.

using Content.Shared._Onyx.NanoChat;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Onyx.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class OnyxNanoChatGroupEntry : BoxContainer
{
    private static readonly Color SelectedColor = Color.FromHex("#173717d9");

    public event Action<uint>? OnPressed;
    private uint _id;
    private Action<EventArgs>? _pressHandler;

    public OnyxNanoChatGroupEntry()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetGroup(NanoChatGroup group, bool isSelected)
    {
        if (_pressHandler != null)
            ChatButton.OnPressed -= _pressHandler;

        _id = group.Id;
        _pressHandler = _ => OnPressed?.Invoke(_id);
        ChatButton.OnPressed += _pressHandler;

        NameLabel.Text = FormattedMessage.EscapeText(group.Name);
        MembersLabel.Text = Loc.GetString("nano-chat-group-members", ("count", group.MemberCount));
        UnreadIndicator.Visible = group.HasUnread;
        ChatButton.ModulateSelfOverride = isSelected ? SelectedColor : null;
        ChatButton.ToolTip = $"#{group.Id}";
    }
}
