// Space Onyx
// Copyright (C) 2026 Space Onyx contributors
//
// This file is licensed under AGPL-3.0-or-later.
// See LICENSES for the full license text.

using System.Linq;
using System.Numerics;
using Content.Client._DV.CartridgeLoader.Cartridges;
using Content.Shared._DV.CartridgeLoader.Cartridges;
using Content.Shared._Onyx.NanoChat;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._Onyx.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class OnyxNanoChatUiFragment : BoxContainer
{
    [Dependency] private IGameTiming _timing = default!;

    private readonly NewChatPopup _newChatPopup;
    private readonly OnyxNanoChatCreateGroupPopup _createGroupPopup;
    private readonly OnyxNanoChatJoinGroupPopup _joinGroupPopup;

    private uint? _currentChat;
    private uint? _pendingChat;
    private uint _ownNumber;
    private bool _notificationsMuted;
    private bool _listNumber = true;
    private Dictionary<uint, NanoChatRecipient> _recipients = new();
    private Dictionary<uint, NanoChatGroup> _groups = new();
    private Dictionary<uint, List<NanoChatMessage>> _messages = new();

    public event Action<NanoChatUiMessageType, uint?, string?, string?>? OnMessageSent;

    public OnyxNanoChatUiFragment()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        _newChatPopup = new NewChatPopup();
        _createGroupPopup = new OnyxNanoChatCreateGroupPopup();
        _joinGroupPopup = new OnyxNanoChatJoinGroupPopup();

        ChatTabs.SetTabTitle(0, Loc.GetString("nano-chat-tab-contacts"));
        ChatTabs.SetTabTitle(1, Loc.GetString("nano-chat-tab-groups"));

        SetupEventHandlers();
    }

    private void SetupEventHandlers()
    {
        _newChatPopup.OnChatCreated += (number, name, job) =>
        {
            OnMessageSent?.Invoke(NanoChatUiMessageType.NewChat, number, name, job);
        };

        _createGroupPopup.OnGroupCreated += name =>
        {
            OnMessageSent?.Invoke(NanoChatUiMessageType.CreateGroup, null, name, null);
        };

        _joinGroupPopup.OnGroupJoined += id =>
        {
            OnMessageSent?.Invoke(NanoChatUiMessageType.JoinGroup, id, null, null);
        };

        NewChatButton.OnPressed += _ =>
        {
            _newChatPopup.ClearInputs();
            _newChatPopup.OpenCentered();
        };

        CreateGroupButton.OnPressed += _ =>
        {
            _createGroupPopup.ClearInputs();
            _createGroupPopup.OpenCentered();
        };

        JoinGroupButton.OnPressed += _ =>
        {
            _joinGroupPopup.ClearInputs();
            _joinGroupPopup.OpenCentered();
        };

        MuteButton.OnPressed += _ =>
        {
            _notificationsMuted = !_notificationsMuted;
            UpdateMuteButton();
            OnMessageSent?.Invoke(NanoChatUiMessageType.ToggleMute, null, null, null);
        };

        ListNumberButton.OnPressed += _ =>
        {
            _listNumber = !_listNumber;
            UpdateListNumber();
            OnMessageSent?.Invoke(NanoChatUiMessageType.ToggleListNumber, null, null, null);
        };

        MessageInput.OnTextChanged += args =>
        {
            var length = args.Text.Length;
            var isValid = !string.IsNullOrWhiteSpace(args.Text) &&
                          length <= NanoChatMessage.MaxContentLength &&
                          (_currentChat != null || _pendingChat != null);

            SendButton.Disabled = !isValid;

            CharacterCount.Visible = length > NanoChatMessage.MaxContentLength;
            if (length > NanoChatMessage.MaxContentLength)
            {
                CharacterCount.Text = Loc.GetString("nano-chat-message-too-long",
                    ("current", length),
                    ("max", NanoChatMessage.MaxContentLength));
            }
        };

        MessageInput.OnTextEntered += _ => SendMessage();
        SendButton.OnPressed += _ => SendMessage();
        DeleteChatButton.OnPressed += _ => DeleteCurrentChat();
        LeaveGroupButton.OnPressed += _ => LeaveCurrentGroup();

        LookupButton.OnPressed += _ => ToggleView();
        LookupView.OnStartChat += contact =>
        {
            OnMessageSent?.Invoke(NanoChatUiMessageType.NewChat, contact.Number, contact.Name, contact.JobTitle);
            SelectChat(contact.Number);
            ToggleView();
        };
    }

    private void ToggleView()
    {
        ChatView.Visible = !ChatView.Visible;
        LookupView.Visible = !ChatView.Visible;
        LookupButton.Pressed = LookupView.Visible;
    }

    private void SendMessage()
    {
        var activeChat = _pendingChat ?? _currentChat;
        if (activeChat == null || string.IsNullOrWhiteSpace(MessageInput.Text))
            return;

        var messageContent = MessageInput.Text.Trim();
        if (messageContent.Length > NanoChatMessage.MaxContentLength)
            messageContent = messageContent[..NanoChatMessage.MaxContentLength];

        var predictedMessage = new NanoChatMessage(
            _timing.CurTime,
            messageContent,
            _ownNumber);

        if (!_messages.TryGetValue(activeChat.Value, out var value))
        {
            value = new List<NanoChatMessage>();
            _messages[activeChat.Value] = value;
        }

        value.Add(predictedMessage);
        UpdateMessages(_messages);

        OnMessageSent?.Invoke(NanoChatUiMessageType.SendMessage, activeChat, messageContent, null);

        MessageInput.Text = string.Empty;
        SendButton.Disabled = true;
    }

    private void SelectChat(uint number)
    {
        if (_currentChat == number && _pendingChat == null)
            return;

        _pendingChat = number;

        if (_recipients.TryGetValue(number, out var recipient))
        {
            recipient.HasUnread = false;
            _recipients[number] = recipient;
            UpdateChatList(_recipients);
        }

        if (_groups.TryGetValue(number, out var group))
        {
            _groups[number] = group with { HasUnread = false };
            UpdateGroupList(_groups);
        }

        OnMessageSent?.Invoke(NanoChatUiMessageType.SelectChat, number, null, null);
        UpdateCurrentChat();
    }

    private void DeleteCurrentChat()
    {
        var activeChat = _pendingChat ?? _currentChat;
        if (activeChat == null)
            return;

        OnMessageSent?.Invoke(NanoChatUiMessageType.DeleteChat, activeChat, null, null);
    }

    private void LeaveCurrentGroup()
    {
        var activeChat = _pendingChat ?? _currentChat;
        if (activeChat == null || !_groups.ContainsKey(activeChat.Value))
            return;

        OnMessageSent?.Invoke(NanoChatUiMessageType.LeaveGroup, activeChat, null, null);
        _currentChat = null;
        _pendingChat = null;
        UpdateCurrentChat();
    }

    private void UpdateChatList(Dictionary<uint, NanoChatRecipient> recipients)
    {
        _recipients = recipients;
        ContactsList.RemoveAllChildren();

        if (recipients.Count == 0)
        {
            NoChatsLabel.Visible = true;
            ContactsList.AddChild(NoChatsLabel);
            return;
        }

        NoChatsLabel.Visible = false;

        foreach (var (number, recipient) in recipients.OrderBy(r => r.Value.Name))
        {
            var entry = new NanoChatEntry();
            var isSelected = _pendingChat == number || (_pendingChat == null && _currentChat == number);
            entry.SetRecipient(recipient, number, isSelected);
            entry.OnPressed += SelectChat;
            ContactsList.AddChild(entry);
        }
    }

    private void UpdateGroupList(Dictionary<uint, NanoChatGroup> groups)
    {
        _groups = groups;
        GroupsList.RemoveAllChildren();

        if (groups.Count == 0)
        {
            NoGroupsLabel.Visible = true;
            GroupsList.AddChild(NoGroupsLabel);
            return;
        }

        NoGroupsLabel.Visible = false;

        foreach (var (id, group) in groups.OrderBy(g => g.Value.Name))
        {
            var entry = new OnyxNanoChatGroupEntry();
            var isSelected = _pendingChat == id || (_pendingChat == null && _currentChat == id);
            entry.SetGroup(group, isSelected);
            entry.OnPressed += SelectChat;
            GroupsList.AddChild(entry);
        }
    }

    private void UpdateCurrentChat()
    {
        var activeChat = _pendingChat ?? _currentChat;
        var hasActiveChat = activeChat != null;
        var isGroup = activeChat != null && _groups.ContainsKey(activeChat.Value);

        MessagesScroll.Visible = hasActiveChat;
        MessageInputContainer.Visible = hasActiveChat;
        DeleteChatButton.Visible = hasActiveChat && !isGroup;
        LeaveGroupButton.Visible = hasActiveChat && isGroup;
        GroupMembersLabel.Visible = isGroup;

        if (activeChat == null)
        {
            CurrentChatName.Text = Loc.GetString("nano-chat-select-chat");
            GroupMembersLabel.Text = string.Empty;
            return;
        }

        if (isGroup && _groups.TryGetValue(activeChat.Value, out var group))
        {
            CurrentChatName.Text = group.Name;
            GroupMembersLabel.Text = Loc.GetString("nano-chat-group-members", ("count", group.MemberCount));
            return;
        }

        GroupMembersLabel.Text = string.Empty;

        if (_recipients.TryGetValue(activeChat.Value, out var recipient))
        {
            CurrentChatName.Text = recipient.Name +
                (string.IsNullOrEmpty(recipient.JobTitle) ? "" : $" ({recipient.JobTitle})");
        }
        else
        {
            CurrentChatName.Text = Loc.GetString("nano-chat-select-chat");
        }
    }

    private void UpdateMessages(Dictionary<uint, List<NanoChatMessage>> messages)
    {
        _messages = messages;
        MessageList.RemoveAllChildren();

        var activeChat = _pendingChat ?? _currentChat;
        if (activeChat == null || !messages.TryGetValue(activeChat.Value, out var chatMessages))
            return;

        var isGroup = _groups.ContainsKey(activeChat.Value);

        foreach (var message in chatMessages)
        {
            if (message.SenderId == NanoChatMessage.SystemSenderId)
            {
                MessageList.AddChild(new Label
                {
                    Text = message.Content,
                    HorizontalAlignment = HAlignment.Center,
                    StyleClasses = { "LabelSubText" },
                    Margin = new Thickness(0, 2),
                });
            }
            else
            {
                var isOwnMessage = message.SenderId == _ownNumber;
                var bubble = new NanoChatMessageBubble();
                bubble.SetMessage(message, isOwnMessage, isGroup && !isOwnMessage);
                MessageList.AddChild(bubble);
            }

            MessageList.AddChild(new Control { MinSize = new Vector2(0, 4) });
        }

        MessageList.InvalidateMeasure();
        MessagesScroll.InvalidateMeasure();
        MessagesScroll.SetScrollValue(new Vector2(0, float.MaxValue));
    }

    private void UpdateMuteButton()
    {
        BellMutedIcon.Visible = _notificationsMuted;
    }

    private void UpdateListNumber()
    {
        ListNumberButton.Pressed = _listNumber;
    }

    public void UpdateState(NanoChatUiState state)
    {
        _ownNumber = state.OwnNumber;
        _notificationsMuted = state.NotificationsMuted;
        _listNumber = state.ListNumber;
        OwnNumberLabel.Text = $"#{state.OwnNumber:D4}";
        UpdateMuteButton();
        UpdateListNumber();

        var atLimit = state.Recipients.Count >= state.MaxRecipients;
        NewChatButton.Disabled = atLimit;
        NewChatButton.ToolTip = atLimit
            ? Loc.GetString("nano-chat-max-recipients")
            : Loc.GetString("nano-chat-new-chat");

        if (_pendingChat != null)
        {
            if (_pendingChat == state.CurrentChat)
                _currentChat = _pendingChat;

            _pendingChat = null;
        }

        if (_pendingChat == null)
            _currentChat = state.CurrentChat;

        _recipients = state.Recipients;
        _groups = state.Groups;
        _messages = state.Messages;

        UpdateChatList(_recipients);
        UpdateGroupList(_groups);
        UpdateCurrentChat();
        UpdateMessages(_messages);
        LookupView.UpdateContactList(state);
    }

    protected override void Dispose(bool disposing)
    {
        if (disposing)
        {
            _newChatPopup.Dispose();
            _createGroupPopup.Dispose();
            _joinGroupPopup.Dispose();
            OnMessageSent = null;
        }

        base.Dispose(disposing);
    }
}
