// Space Onyx
// Copyright (C) 2026 Space Onyx contributors
//
// This file is licensed under AGPL-3.0-or-later.
// See LICENSES for the full license text.

using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Onyx.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class OnyxNanoChatCreateGroupPopup : DefaultWindow
{
    private const int MaxNameLength = 24;

    public event Action<string>? OnGroupCreated;

    public OnyxNanoChatCreateGroupPopup()
    {
        RobustXamlLoader.Load(this);

        ContentsContainer.Margin = new Thickness(3);

        CancelButton.OnPressed += _ => Close();
        CreateButton.OnPressed += _ => CreateGroup();

        NameInput.OnTextChanged += args =>
        {
            if (args.Text.Length > MaxNameLength)
                NameInput.Text = args.Text[..MaxNameLength];

            Validate();
        };
    }

    private void Validate()
    {
        CreateButton.Disabled = string.IsNullOrWhiteSpace(NameInput.Text);
    }

    private void CreateGroup()
    {
        var name = NameInput.Text.Trim();
        if (string.IsNullOrWhiteSpace(name))
            return;

        OnGroupCreated?.Invoke(name);
        Close();
    }

    public void ClearInputs()
    {
        NameInput.Text = string.Empty;
        Validate();
    }
}
