// Space Onyx
// Copyright (C) 2026 Space Onyx contributors
//
// This file is licensed under AGPL-3.0-or-later.
// See LICENSES for the full license text.

using System.Linq;
using Content.Shared._Onyx.NanoChat;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Onyx.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class OnyxNanoChatJoinGroupPopup : DefaultWindow
{
    private const int MaxIdLength = 8;

    public event Action<uint>? OnGroupJoined;

    public OnyxNanoChatJoinGroupPopup()
    {
        RobustXamlLoader.Load(this);

        ContentsContainer.Margin = new Thickness(3);

        CancelButton.OnPressed += _ => Close();
        JoinButton.OnPressed += _ => JoinGroup();

        IdInput.OnTextChanged += args =>
        {
            if (args.Text.Length > MaxIdLength)
                IdInput.Text = args.Text[..MaxIdLength];

            var digitsOnly = string.Concat(IdInput.Text.Where(char.IsDigit));
            if (digitsOnly != IdInput.Text)
                IdInput.Text = digitsOnly;

            Validate();
        };
    }

    private void Validate()
    {
        JoinButton.Disabled = !uint.TryParse(IdInput.Text, out var id) || id < NanoChatGroup.FirstGroupId;
    }

    private void JoinGroup()
    {
        if (!uint.TryParse(IdInput.Text, out var id) || id < NanoChatGroup.FirstGroupId)
            return;

        OnGroupJoined?.Invoke(id);
        Close();
    }

    public void ClearInputs()
    {
        IdInput.Text = string.Empty;
        Validate();
    }
}
