// Space Onyx
// Copyright (C) 2026 Space Onyx contributors
//
// This file is licensed under AGPL-3.0-or-later.
// See LICENSES for the full license text.

using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using System.Linq;
using Content.Shared._Onyx.NanoChat;

namespace Content.Client._Onyx.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class OnyxNanoChatCreateGroupPopup : DefaultWindow
{
    private const int MaxNameLength = 24;
    private const int MaxIdLength = 10;

    public event Action<string, uint?>? OnGroupCreated;

    public OnyxNanoChatCreateGroupPopup()
    {
        RobustXamlLoader.Load(this);

        ContentsContainer.Margin = new Thickness(3);

        CancelButton.OnPressed += _ => Close();
        CreateButton.OnPressed += _ => CreateGroup();

        NameInput.OnTextChanged += args =>
        {
            if (args.Text.Length > MaxNameLength)
                NameInput.Text = args.Text[..MaxNameLength];

            Validate();
        };

        IdInput.OnTextChanged += args =>
        {
            if (args.Text.Length > MaxIdLength)
                IdInput.Text = args.Text[..MaxIdLength];

            var digitsOnly = string.Concat(IdInput.Text.Where(char.IsDigit));
            if (digitsOnly != IdInput.Text)
                IdInput.Text = digitsOnly;

            Validate();
        };
    }

    private void Validate()
    {
        if (string.IsNullOrWhiteSpace(NameInput.Text))
        {
            CreateButton.Disabled = true;
            return;
        }

        if (string.IsNullOrWhiteSpace(IdInput.Text))
        {
            CreateButton.Disabled = false;
            return;
        }

        CreateButton.Disabled = !uint.TryParse(IdInput.Text, out var id) || id < NanoChatGroup.FirstGroupId;
    }

    private void CreateGroup()
    {
        var name = NameInput.Text.Trim();
        if (string.IsNullOrWhiteSpace(name))
            return;

        uint? desiredId = null;
        if (!string.IsNullOrWhiteSpace(IdInput.Text))
        {
            if (!uint.TryParse(IdInput.Text, out var id) || id < NanoChatGroup.FirstGroupId)
                return;

            desiredId = id;
        }

        OnGroupCreated?.Invoke(name, desiredId);
        Close();
    }

    public void ClearInputs()
    {
        NameInput.Text = string.Empty;
        IdInput.Text = string.Empty;
        Validate();
    }
}
