// Content taken from Wega (https://github.com/wega-team/ss14-wega), licensed under GNU GPL v3.
using Content.Client.Stylesheets;
using Content.Shared.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Onyx.Lobby.UI;

[GenerateTypedNameReferences]
public sealed partial class CharacterDescriptionEditor : Control
{
    public event Action<CharacterDescriptionField, string>? DescriptionChanged;
    private bool _updatingProfile;

    public CharacterDescriptionEditor()
    {
        RobustXamlLoader.Load(this);

        EditorTabs.SetTabTitle(0, Loc.GetString("flavor-tab-flavor"));
        EditorTabs.SetTabTitle(1, Loc.GetString("flavor-tab-character"));
        EditorTabs.SetTabTitle(2, Loc.GetString("flavor-tab-ooc-flavor"));
        EditorTabs.SetTabTitle(3, Loc.GetString("flavor-tab-preview"));
        PreviewTabs.SetTabTitle(0, Loc.GetString("flavor-tab-flavor"));
        PreviewTabs.SetTabTitle(1, Loc.GetString("flavor-tab-character"));

        Bind(AppearanceInput, CharacterDescriptionField.Appearance, "flavor-text-placeholder");
        Bind(CharacterInput, CharacterDescriptionField.Character, "character-flavor-text-placeholder");
        Bind(OocInput, CharacterDescriptionField.Ooc, "ooc-flavor-text-placeholder");
        Bind(TagsInput, CharacterDescriptionField.Tags, "tags-flavor-text-placeholder");
        Bind(LinksInput, CharacterDescriptionField.Links, "links-flavor-text-placeholder");
    }

    public void SetProfile(HumanoidCharacterProfile? profile)
    {
        _updatingProfile = true;
        AppearanceInput.TextRope = new Rope.Leaf(profile?.FlavorText ?? string.Empty);
        CharacterInput.TextRope = new Rope.Leaf(profile?.CharacterFlavorText ?? string.Empty);
        OocInput.TextRope = new Rope.Leaf(profile?.OOCFlavorText ?? string.Empty);
        TagsInput.TextRope = new Rope.Leaf(profile?.TagsFlavorText ?? string.Empty);
        LinksInput.TextRope = new Rope.Leaf(profile?.LinksFlavorText ?? string.Empty);
        _updatingProfile = false;
        UpdatePreview(profile, true);
    }

    public void UpdatePreview(HumanoidCharacterProfile? profile, bool reloadCharacter = false)
    {
        if (profile == null)
            return;

        if (reloadCharacter)
            CharacterPreview.LoadPreview(profile, showClothes: false);
        PreviewName.Text = profile.Name;
        var species = Loc.GetString($"species-name-{profile.Species.ToString().ToLowerInvariant()}");
        var sex = Loc.GetString($"humanoid-profile-editor-sex-{profile.Sex.ToString().ToLowerInvariant()}-text");
        var gender = Loc.GetString($"humanoid-profile-editor-pronouns-{profile.Gender.ToString().ToLowerInvariant()}-text");
        PreviewDetails.Text = $"{species} | {sex} | {gender}";
        AppearancePreview.SetMessage(profile.FlavorText);
        CharacterTextPreview.SetMessage(profile.CharacterFlavorText);
        OocPreview.SetMessage(profile.OOCFlavorText);
        TagsPreview.Text = profile.TagsFlavorText;

        UpdateLinks(profile.LinksFlavorText);
    }

    private void Bind(TextEdit input, CharacterDescriptionField field, string placeholder)
    {
        input.Placeholder = new Rope.Leaf(Loc.GetString(placeholder));
        input.OnTextChanged += _ =>
        {
            if (!_updatingProfile)
                DescriptionChanged?.Invoke(field, Rope.Collapse(input.TextRope).Trim());
        };
    }

    private void UpdateLinks(string linksText)
    {
        LinksPreview.RemoveAllChildren();
        foreach (var link in linksText.Split([',', ' ', '\n', '\r', '\t'], StringSplitOptions.RemoveEmptyEntries))
        {
            if (!link.StartsWith("http://", StringComparison.OrdinalIgnoreCase) &&
                !link.StartsWith("https://", StringComparison.OrdinalIgnoreCase) &&
                !link.StartsWith("www.", StringComparison.OrdinalIgnoreCase))
            {
                LinksPreview.AddChild(new Label { Text = link, HorizontalAlignment = HAlignment.Center });
                continue;
            }

            var url = link.StartsWith("www.", StringComparison.OrdinalIgnoreCase) ? $"https://{link}" : link;
            var button = new Button
            {
                Text = link.Length > 40 ? $"{link[..37]}..." : link,
                ToolTip = Loc.GetString("humanoid-profile-editor-link-tooltip", ("url", link)),
                StyleClasses = { StyleClass.ButtonOpenBoth },
            };
            button.OnPressed += _ => IoCManager.Resolve<IUriOpener>().OpenUri(url);
            LinksPreview.AddChild(button);
        }
    }
}

public enum CharacterDescriptionField
{
    Appearance,
    Character,
    Ooc,
    Tags,
    Links,
}
