using Content.Client._Onyx.Discord;
using Content.Shared._Onyx.Discord;
using Content.Shared.CCVar;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Utility;

namespace Content.Client.Lobby.UI;

[GenerateTypedNameReferences]
[UsedImplicitly]
public sealed partial class DiscordLinkWindow : DefaultWindow
{
    [Dependency] private IClipboardManager _clipboard = default!;
    [Dependency] private IPlayerManager _player = default!;
    [Dependency] private DiscordIdManager _discordIdManager = default!;
    [Dependency] private IUriOpener _uriOpener = default!;
    [Dependency] private IConfigurationManager _cfg = default!;

    private const string UnknownString = "UNKNOWN";
    private const string DefaultChannelLink = "https://discord.com";
    private string? _discordId;
    private string? _discordUsername;
    private string? _linkCode;
    private string _plainInstruction = string.Empty;
    private readonly string _channelLink;

    public DiscordLinkWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        var channel = _cfg.GetCVar(CCVars.DiscordLinkChannel);
        _channelLink = string.IsNullOrWhiteSpace(channel) ? DefaultChannelLink : channel;

        CopyCodeButton.OnPressed += _ => _clipboard.SetText(_linkCode ?? UnknownString);
        OpenDiscordButton.OnPressed += _ => _uriOpener.OpenUri(_channelLink);
        CopyInstructionButton.OnPressed += _ => _clipboard.SetText(_plainInstruction);
        UnlinkDiscordButton.OnPressed += _ =>
        {
            UnlinkDiscordButton.Disabled = true;
            StatusLabel.Text = Loc.GetString("ui-lobby-discord-link-unlink-pending");
            _discordIdManager.RequestUnlink();
        };
        UpdateStatus();
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();
        _discordIdManager.DiscordInfoUpdated += UpdateStatus;
    }

    protected override void ExitedTree()
    {
        _discordIdManager.DiscordInfoUpdated -= UpdateStatus;
        base.ExitedTree();
    }

    protected override void Opened()
    {
        base.Opened();
        _discordIdManager.RequestDiscordInfo();
        UpdateStatus();
    }

    private void UpdateStatus()
    {
        _discordId = _discordIdManager.TryGetDiscordId(out var discordId) ? discordId : null;
        _discordUsername = _discordIdManager.TryGetDiscordUsername(out var username) ? username : null;
        _linkCode = _discordIdManager.TryGetLinkCode(out var code) ? code : null;
        UnlinkDiscordButton.Disabled = false;
        StatusLabel.Text = _discordIdManager.Result switch
        {
            DiscordLinkResult.UnlinkSucceeded => Loc.GetString("ui-lobby-discord-link-unlink-success"),
            DiscordLinkResult.UnlinkFailed => Loc.GetString("ui-lobby-discord-link-unlink-failed"),
            _ when _discordId == null && _linkCode == null => Loc.GetString("ui-lobby-discord-link-loading"),
            _ => string.Empty
        };

        if (_discordId != null)
        {
            var lines = new[]
            {
                Loc.GetString("ui-lobby-discord-link-success-line1"),
                Loc.GetString("ui-lobby-discord-link-success-line2", ("username", FormattedMessage.EscapeText(_discordUsername ?? UnknownString)), ("discordId", FormattedMessage.EscapeText(_discordId))),
                Loc.GetString("ui-lobby-discord-link-success-line3", ("username", FormattedMessage.EscapeText(_player.LocalSession?.Name ?? UnknownString)))
            };
            var message = new FormattedMessage();
            message.AddMarkupOrThrow(string.Join("\n", lines));
            SuccessRichText.SetMessage(message);
            InstructionContainer.Visible = false;
            SuccessContainer.Visible = true;
            return;
        }

        if (_linkCode == null)
        {
            InstructionContainer.Visible = false;
            SuccessContainer.Visible = false;
            return;
        }

        var ckey = _player.LocalSession?.Name ?? UnknownString;
        var instructions = new[]
        {
            Loc.GetString("ui-lobby-discord-link-instructions-line1"),
            Loc.GetString("ui-lobby-discord-link-instructions-line2", ("code", FormattedMessage.EscapeText(_linkCode))),
            Loc.GetString("ui-lobby-discord-link-instructions-line3", ("ckey", FormattedMessage.EscapeText(ckey))),
            Loc.GetString("ui-lobby-discord-link-instructions-line4", ("channelLink", FormattedMessage.EscapeText(_channelLink))),
            Loc.GetString("ui-lobby-discord-link-instructions-line5")
        };
        _plainInstruction = string.Join("\n", new[]
        {
            Loc.GetString("ui-lobby-discord-link-instructions-plain-line1"),
            Loc.GetString("ui-lobby-discord-link-instructions-plain-line2", ("code", _linkCode)),
            Loc.GetString("ui-lobby-discord-link-instructions-plain-line3", ("ckey", ckey)),
            Loc.GetString("ui-lobby-discord-link-instructions-plain-line4", ("channelLink", _channelLink)),
            Loc.GetString("ui-lobby-discord-link-instructions-plain-line5")
        });
        var instructionMessage = new FormattedMessage();
        instructionMessage.AddMarkupOrThrow(string.Join("\n", instructions));
        InstructionText.SetMessage(instructionMessage);
        InstructionContainer.Visible = true;
        SuccessContainer.Visible = false;
    }

}
