- type: job
  id: BlueshieldOfficer
  name: job-name-bs
  playTimeTracker: JobBlueshieldOfficer
  requirements:
  - !type:DepartmentTimeRequirement
    department: Command
    time: 90000
  - !type:DepartmentTimeRequirement
    department: Medical
    time: 54000
  - !type:DepartmentTimeRequirement
    department: Security
    time: 108000
  - !type:AgeRequirement
    requiredAge: 21
  - !type:RoleTimeRequirement
    role: JobSurgeon
    time: 7200
  - !type:RoleTimeRequirement
    role: JobCaptain
    time: 7200
  - !type:SpeciesRequirement
    inverted: true
    species:
    - Felinid
  guides:
  - Command
  startingGear: BlueshieldOfficerGear
  icon: JobIconBlueshield
  joinNotifyCrew: true
  supervisors: job-supervisors-ntr-centcom
  contracts:
  - DocumentContractEmploymentCommand
  canBeAntag: false
  access:
  - Security
  - Brig
  - External
  - Cryogenics
  - Maintenance
  - Engineering
  - Medical
  - Research
  - Command
  - CentralCommand
  - BlueshieldOfficer
  - Service
  - Hydroponics
  - Cargo
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, BluespaceLifelineImplant ]
  - !type:AddComponentSpecial
    components:
    - type: CommandStaff

- type: startingGear
  id: BlueshieldOfficerGear
  equipment:
    eyes: ClothingEyesGlassesBSO
    id: BlueshieldPDA
    ears: ClothingHeadsetAltBlueshield
    belt: ClothingBeltAssaultFilled
    pocket1: UniqueBlueshieldOfficerLockerTeleporter
  storage:
    back:
    - Flash
    - CombatKnife

- type: chameleonOutfit
  id: BlueshieldOfficerChameleonOutfit
  job: BlueshieldOfficer
  equipment:
    head: ClothingHeadHatBeretBlueshield
    eyes: ClothingEyesGlassesBSO
    mask: ClothingMaskGasSecurity
    ears: ClothingHeadsetAltBlueshield
    outerClothing: ClothingBlueshieldArmourVest
    neck: ClothingNeckMantleBlueshield
    gloves: ClothingHandsGlovesCombat
    jumpsuit: ClothingUniformJumpsuitBlueshieldOfficer
    id: BlueshieldPDA
    back: ClothingBackpackBlueshield
    shoes: ClothingShoesBootsJack
