// Space Onyx
// Copyright (C) 2026 Space Onyx contributors
//
// This file is licensed under AGPL-3.0-or-later.
// See LICENSES for the full license text.

using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Onyx.Guidebook.Controls;

[GenerateTypedNameReferences]
public sealed partial class GuidebookToolbar : BoxContainer
{
    public GuidebookToolbar()
    {
        RobustXamlLoader.Load(this);
    }
}
