// Space Onyx
// Copyright (C) 2026 Space Onyx contributors
//
// This file is licensed under AGPL-3.0-or-later.
// See LICENSES for the full license text.

using System.Linq;
using Content.Client.Stylesheets;
using Content.Shared.CCVar;
using Content.Shared.Preferences;
using Content.Shared.Traits;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Configuration;

namespace Content.Client._Onyx.Lobby.UI.Traits;

[GenerateTypedNameReferences]
public sealed partial class TraitsPersonalizationControl : BoxContainer
{
    private readonly IPrototypeManager _prototypeManager;
    private readonly IConfigurationManager _configurationManager;
    private readonly List<(Control Control, string SearchText)> _searchEntries = [];
    private readonly Dictionary<string, (Label Label, int Max)> _categoryCounters = [];

    private HumanoidCharacterProfile? _profile;
    private Action<HumanoidCharacterProfile?>? _profileChanged;

    public TraitsPersonalizationControl()
    {
        RobustXamlLoader.Load(this);
        _prototypeManager = IoCManager.Resolve<IPrototypeManager>();
        _configurationManager = IoCManager.Resolve<IConfigurationManager>();
        SearchBar.OnTextChanged += args => ApplySearch(args.Text);
        PointsBarBackground.OnResized += UpdateProgressBar;
    }

    public void Populate(HumanoidCharacterProfile? profile, Action<HumanoidCharacterProfile?> profileChanged)
    {
        _profile = profile;
        _profileChanged = profileChanged;
        Categories.RemoveAllChildren();
        _searchEntries.Clear();
        _categoryCounters.Clear();

        var traits = _prototypeManager.EnumeratePrototypes<TraitPrototype>()
            .OrderBy(trait => Loc.GetString(trait.Name))
            .ToList();

        if (traits.Count == 0)
        {
            Categories.AddChild(new Label
            {
                Text = Loc.GetString("humanoid-profile-editor-no-traits"),
                StyleClasses = { StyleClass.LabelWeak },
            });
            UpdateSummary();
            return;
        }

        var groups = traits.GroupBy(trait => trait.Category?.Id ?? TraitCategoryPrototype.Default);
        foreach (var group in groups)
            AddCategory(group.Key, group);

        ApplySearch(SearchBar.Text);
        UpdateSummary();
    }

    private void AddCategory(string categoryId, IEnumerable<TraitPrototype> traits)
    {
        TraitCategoryPrototype? category = null;
        if (categoryId != TraitCategoryPrototype.Default &&
            !_prototypeManager.TryIndex(categoryId, out category))
        {
            return;
        }

        var selectedCount = traits.Count(trait => _profile?.TraitPreferences.Contains(trait.ID) == true);

        var categoryContainer = new BoxContainer
        {
            Orientation = LayoutOrientation.Vertical,
            HorizontalExpand = true,
            Margin = new Thickness(0, 0, 0, 8),
        };

        if (category is not null)
        {
            var header = new BoxContainer
            {
                Orientation = LayoutOrientation.Horizontal,
                Margin = new Thickness(8, 6),
            };
            header.AddChild(new Label
            {
                Text = Loc.GetString(category.Name),
                StyleClasses = { StyleClass.LabelHeading },
                HorizontalExpand = true,
            });

            if (category.MaxTraits is { } maxTraits)
            {
                var counter = new Label
                {
                    Text = Loc.GetString("trait-personalization-category-count",
                        ("current", selectedCount),
                        ("max", maxTraits)),
                    StyleClasses = { StyleClass.LabelWeak },
                };
                header.AddChild(counter);
                _categoryCounters[categoryId] = (counter, maxTraits);
            }

            categoryContainer.AddChild(new PanelContainer
            {
                StyleClasses = { "OnyxTraitCategoryHeader" },
                Children = { header },
            });
            categoryContainer.AddChild(new PanelContainer
            {
                StyleClasses = { "OnyxTraitCategoryAccent" },
                SetHeight = 3,
            });
        }

        var cards = new BoxContainer
        {
            Orientation = LayoutOrientation.Vertical,
            HorizontalExpand = true,
            Margin = new Thickness(8),
        };

        foreach (var trait in traits)
        {
            var card = new TraitPreferenceCard(trait)
            {
                Preference = _profile?.TraitPreferences.Contains(trait.ID) == true,
            };
            card.PreferenceChanged += selected => OnTraitChanged(trait, card, selected);
            cards.AddChild(card);

            var description = trait.Description is { } descriptionId
                ? Loc.GetString(descriptionId)
                : string.Empty;
            _searchEntries.Add((card, $"{Loc.GetString(trait.Name)} {description}"));
        }

        categoryContainer.AddChild(new PanelContainer
        {
            StyleClasses = { "OnyxTraitCategoryContent" },
            Children = { cards },
        });

        Categories.AddChild(categoryContainer);
    }

    private void OnTraitChanged(TraitPrototype trait, TraitPreferenceCard card, bool selected)
    {
        var oldProfile = _profile;
        _profile = selected
            ? _profile?.WithTraitPreference(trait.ID, _prototypeManager, _configurationManager)
            : _profile?.WithoutTraitPreference(trait.ID, _prototypeManager, _configurationManager);

        if (oldProfile is null
                ? _profile is null
                : _profile is not null && oldProfile.TraitPreferences.SetEquals(_profile.TraitPreferences))
        {
            card.SetPreferenceSilently(_profile?.TraitPreferences.Contains(trait.ID) == true);
            return;
        }

        UpdateSummary();
        UpdateCategoryCounters();
        _profileChanged?.Invoke(_profile);
    }

    private void ApplySearch(string text)
    {
        foreach (var (control, searchText) in _searchEntries)
            control.Visible = string.IsNullOrWhiteSpace(text) ||
                              searchText.Contains(text, StringComparison.OrdinalIgnoreCase);
    }

    private void UpdateSummary()
    {
        var spent = 0;
        if (_profile is not null)
        {
            foreach (var traitId in _profile.TraitPreferences)
            {
                if (_prototypeManager.TryIndex(traitId, out TraitPrototype? trait))
                    spent += trait.Cost;
            }
        }

        var maxPoints = Math.Max(0, _configurationManager.GetCVar(CCVars.MaxTraitPoints));
        SelectionSummary.Text = Loc.GetString("trait-personalization-balance",
            ("current", spent),
            ("max", maxPoints));
        UpdateProgressBar(spent, maxPoints);
    }

    private void UpdateProgressBar()
    {
        var spent = _profile?.TraitPreferences.Sum(id =>
            _prototypeManager.TryIndex(id, out TraitPrototype? trait) ? trait.Cost : 0) ?? 0;
        UpdateProgressBar(spent, Math.Max(0, _configurationManager.GetCVar(CCVars.MaxTraitPoints)));
    }

    private void UpdateProgressBar(int spent, int maxPoints)
    {
        var remaining = Math.Clamp(maxPoints - spent, 0, maxPoints);
        var percentage = maxPoints > 0 ? (float) remaining / maxPoints : 0f;
        PointsBar.SetWidth = Math.Max(0f, PointsBarBackground.Width - 2f) * percentage;

        PointsBar.RemoveStyleClass("OnyxTraitsProgressFull");
        PointsBar.RemoveStyleClass("OnyxTraitsProgressPartial");
        PointsBar.RemoveStyleClass("OnyxTraitsProgressLow");
        PointsBar.RemoveStyleClass("OnyxTraitsProgressEmpty");
        PointsBar.AddStyleClass(percentage switch
        {
            >= 0.75f => "OnyxTraitsProgressFull",
            >= 0.4f => "OnyxTraitsProgressPartial",
            > 0f => "OnyxTraitsProgressLow",
            _ => "OnyxTraitsProgressEmpty",
        });
    }

    private void UpdateCategoryCounters()
    {
        foreach (var (categoryId, counter) in _categoryCounters)
        {
            var selected = _profile?.TraitPreferences.Count(id =>
                _prototypeManager.TryIndex(id, out TraitPrototype? trait) &&
                trait.Category?.Id == categoryId) ?? 0;
            counter.Label.Text = Loc.GetString("trait-personalization-category-count",
                ("current", selected),
                ("max", counter.Max));
        }
    }
}
