- type: job
  id: Reporter
  name: job-name-reporter
  description: job-description-reporter
  playTimeTracker: JobReporter
  startingGear: ReporterGear
  icon: "JobIconReporter"
  supervisors: job-supervisors-hop
  # <Onyx-Contracts>
  contracts:
  - DocumentContractEmploymentService
  # </Onyx-Contracts>
  access:
  - Service
  - Maintenance

- type: startingGear
  id: ReporterGear
  equipment:
    shoes: ClothingShoesColorWhite
    id: ReporterPDA
    ears: ClothingHeadsetService
  # <Onyx-PhotoCamera>
  storage:
    back:
    - PhotoCameraFilled
  # </Onyx-PhotoCamera>

- type: chameleonOutfit
  id: ReporterChameleonOutfit
  job: Reporter
  equipment:
    head: ClothingHeadHatFedoraGrey
    eyes: ClothingEyesGlassesCheapSunglasses
    mask: ClothingMaskBreath
    outerClothing: ClothingOuterCoatTrench
    tie: ClothingNeckTieRed # <Onyx-InventorySubslots-edited>
    gloves: ClothingHandsGlovesFingerless
