// Space Onyx
// Copyright (C) 2026 Space Onyx contributors
//
// This file is licensed under AGPL-3.0-or-later.
// See LICENSES for the full license text.

using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._Onyx.Ghost;

[GenerateTypedNameReferences]
public sealed partial class GhostReturnToLobbyWindow : DefaultWindow
{
    private static readonly TimeSpan ConfirmDelay = TimeSpan.FromSeconds(3);

    [Dependency] private IGameTiming _timing = default!;

    private TimeSpan _openedAt;
    private bool _canConfirm;

    public event Action? OnConfirm;

    public GhostReturnToLobbyWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _openedAt = _timing.RealTime;
        ConfirmButton.OnPressed += _ => OnConfirm?.Invoke();
        UpdateConfirmButton();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        UpdateConfirmButton();
    }

    public void SetCanConfirm(bool canConfirm)
    {
        _canConfirm = canConfirm;
        UpdateConfirmButton();
    }

    private void UpdateConfirmButton()
    {
        var remaining = ConfirmDelay - (_timing.RealTime - _openedAt);
        if (remaining > TimeSpan.Zero)
        {
            var seconds = (int) Math.Ceiling(remaining.TotalSeconds);
            ConfirmButton.Text = $"{Loc.GetString("ghost-return-to-lobby-confirm")} ({seconds})";
            ConfirmButton.Disabled = true;
            return;
        }

        ConfirmButton.Text = Loc.GetString(_canConfirm
            ? "ghost-return-to-lobby-confirm"
            : "ghost-return-to-lobby-insufficient-playtime");
        ConfirmButton.Disabled = !_canConfirm;
    }
}
