using Content.Client.CrewManifest.UI;
using Content.Shared.CrewManifest;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class CrewManifestUiFragment : BoxContainer
{
    private CrewManifestEntries? _entries; // <Onyx-CrewManifest>

    public CrewManifestUiFragment()
    {
        RobustXamlLoader.Load(this);

        StationName.AddStyleClass("LabelBig");
        Orientation = LayoutOrientation.Vertical;
        HorizontalExpand = true;
        VerticalExpand = true;
        SearchLineEdit.OnTextChanged += _ => RefreshListing(); // <Onyx-CrewManifest>
    }

    public void UpdateState(string stationName, CrewManifestEntries? entries)
    {
        _entries = entries; // <Onyx-CrewManifest>

        StationNameContainer.Visible = entries != null;
        StationName.Text = stationName;

        RefreshListing(); // <Onyx-CrewManifest-edited>
    }

    // <Onyx-CrewManifest>
    private void RefreshListing()
    {
        CrewManifestListing.RemoveAllChildren();

        if (_entries != null)
            CrewManifestListing.AddCrewManifestEntries(_entries, SearchLineEdit.Text, true); // <Onyx-CrewManifest-edited>
    }
    // </Onyx-CrewManifest>
}
