using Content.Shared.Body; // <Onyx-MarkingsPersonalization>
using Content.Shared.Humanoid; // <Onyx-MarkingsPersonalization>
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes; // <Onyx-MarkingsPersonalization>

namespace Content.Client.Humanoid;

[GenerateTypedNameReferences]
public sealed partial class MarkingPicker : Control
{
    private MarkingsViewModel? _markingsModel;

    public MarkingPicker()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        UpdateMarkings();
    }

    public void SetModel(MarkingsViewModel model)
    {
        _markingsModel = model;

        _markingsModel.OrganDataChanged += UpdateMarkings;
        _markingsModel.EnforcementsChanged += UpdateMarkings;
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();

        _markingsModel?.OrganDataChanged += UpdateMarkings;
        _markingsModel?.EnforcementsChanged += UpdateMarkings;
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();

        _markingsModel?.OrganDataChanged -= UpdateMarkings;
        _markingsModel?.EnforcementsChanged -= UpdateMarkings;
    }

    private void UpdateMarkings()
    {
        if (_markingsModel is null)
            return;

        // <Onyx-MarkingsPersonalization>
        ProtoId<OrganCategoryPrototype>? selectedOrgan = null;
        HumanoidVisualLayers? selectedLayer = null;
        if (OrganTabs.ChildCount > 0 && OrganTabs.GetChild(OrganTabs.CurrentTab) is OrganMarkingPicker selected)
        {
            selectedOrgan = selected.Organ;
            selectedLayer = selected.SelectedLayer;
        }
        // </Onyx-MarkingsPersonalization>
        OrganTabs.RemoveAllChildren();

        var i = 0;
        var selectedTab = 0; // <Onyx-MarkingsPersonalization>
        foreach (var (organ, organData) in _markingsModel.OrganData)
        {
            var control = new OrganMarkingPicker(_markingsModel, organ, organData.Layers, organData.Group, organ == selectedOrgan ? selectedLayer : null); // <Onyx-MarkingsPersonalization-edited>
            if (control.Empty)
                continue;

            OrganTabs.AddChild(control);
            OrganTabs.SetTabTitle(i, Loc.GetString($"markings-organ-{organ.Id}"));
            if (organ == selectedOrgan)
                selectedTab = i; // <Onyx-MarkingsPersonalization>
            i++;
        }

        if (i > 0)
            OrganTabs.CurrentTab = selectedTab; // <Onyx-MarkingsPersonalization-edited>
        OrganTabs.TabsVisible = i > 1;
    }
}
