using System.Linq;
using Content.Shared.Body;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Markings;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Humanoid;

[GenerateTypedNameReferences]
public sealed partial class OrganMarkingPicker : Control
{
    [Dependency] private MarkingManager _marking = default!;
    [Dependency] private IEntityManager _entity = default!;

    private readonly SpriteSystem _sprite;

    private readonly MarkingsViewModel _markingsModel;
    private readonly HashSet<HumanoidVisualLayers> _layers;
    private readonly ProtoId<MarkingsGroupPrototype> _group;
    private readonly ProtoId<OrganCategoryPrototype> _organ;
    private readonly List<HumanoidVisualLayers> _displayedLayers = new(); // <Onyx-MarkingsPersonalization>
    private HumanoidVisualLayers? _selectedLayer; // <Onyx-MarkingsPersonalization>

    public OrganMarkingPicker(MarkingsViewModel markingsModel, ProtoId<OrganCategoryPrototype> organ, HashSet<HumanoidVisualLayers> layers, ProtoId<MarkingsGroupPrototype> group, HumanoidVisualLayers? selectedLayer = null) // <Onyx-MarkingsPersonalization-edited>
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _markingsModel = markingsModel;
        _layers = layers;
        _group = group;
        _organ = organ;
        _selectedLayer = selectedLayer; // <Onyx-MarkingsPersonalization>

        _sprite = _entity.System<SpriteSystem>();

        UpdateMarkings();
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();

        _markingsModel.OrganProfileDataChanged += OnOrganProfileDataChanged;
        _markingsModel.EnforcementsChanged += UpdateMarkings;
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();

        _markingsModel.OrganProfileDataChanged -= OnOrganProfileDataChanged;
        _markingsModel.EnforcementsChanged -= UpdateMarkings;
    }

    public bool Empty => LayerTabs.ChildCount == 0;
    public ProtoId<OrganCategoryPrototype> Organ => _organ; // <Onyx-MarkingsPersonalization>
    // <Onyx-MarkingsPersonalization>
    public HumanoidVisualLayers? SelectedLayer => LayerTabs.ChildCount > 0 && LayerTabs.CurrentTab < _displayedLayers.Count
        ? _displayedLayers[LayerTabs.CurrentTab]
        : null;
    // </Onyx-MarkingsPersonalization>

    private void OnOrganProfileDataChanged(bool refresh)
    {
        if (refresh)
            UpdateMarkings();
    }

    private void UpdateMarkings()
    {
        if (!_markingsModel.OrganProfileData.TryGetValue(_organ, out var organProfileData))
            return;

        _selectedLayer = SelectedLayer ?? _selectedLayer; // <Onyx-MarkingsPersonalization>
        // <Onyx-MarkingsPersonalizationReset>
        if (LayerTabs.ChildCount > 0)
            LayerTabs.CurrentTab = 0;
        // </Onyx-MarkingsPersonalizationReset>
        LayerTabs.RemoveAllChildren();
        _displayedLayers.Clear(); // <Onyx-MarkingsPersonalization>
        var i = 0;
        var selectedTab = 0; // <Onyx-MarkingsPersonalization>
        foreach (var layer in _layers)
        {
            var allMarkings =
                _markingsModel.EnforceGroupAndSexRestrictions ? _marking.MarkingsByLayerAndGroupAndSex(layer, _group, organProfileData.Sex) : _marking.MarkingsByLayer(layer);

            if (allMarkings.Count == 0)
                continue;

            var control = new LayerMarkingPicker(_markingsModel, _organ, layer, allMarkings);
            LayerTabs.AddChild(control);
            _displayedLayers.Add(layer); // <Onyx-MarkingsPersonalization>
            if (Loc.TryGetString($"markings-layer-{layer}-{_group.Id}", out var layerTitle))
                LayerTabs.SetTabTitle(i, layerTitle);
            else
                LayerTabs.SetTabTitle(i, Loc.GetString($"markings-layer-{layer}"));
            if (layer == _selectedLayer)
                selectedTab = i; // <Onyx-MarkingsPersonalization>
            i++;
        }

        if (i > 0)
            LayerTabs.CurrentTab = selectedTab; // <Onyx-MarkingsPersonalization-edited>
        LayerTabs.TabsVisible = i > 1;
    }
}
