- type: startingGear
  id: AssistantBatGear
  equipment:
    mask: ClothingMaskGas
    jumpsuit: ClothingUniformJumpsuitColorGrey
    shoes: ClothingShoesColorBlack
  inhand:
  - BaseBallBat

- type: startingGear
  id: AssistantAxeGear
  equipment:
    mask: ClothingMaskGas
    jumpsuit: ClothingUniformJumpsuitColorGrey
    shoes: ClothingShoesColorBlack
  inhand:
  - FireAxe

- type: startingGear
  id: AssistantToolboxGear
  equipment:
    mask: ClothingMaskGas
    jumpsuit: ClothingUniformJumpsuitColorGrey
    shoes: ClothingShoesColorBlack
  inhand:
  - ToolboxMechanical

- type: startingGear
  id: AssistantSpearGear
  equipment:
    mask: ClothingMaskGas
    jumpsuit: ClothingUniformJumpsuitColorGrey
    shoes: ClothingShoesColorBlack
  inhand:
  - Spear

- type: startingGear
  id: AbductorAgentNpcGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitAbductor
    shoes: ClothingShoesBootsCombat
    back: ClothingBackpackAbductor

- type: startingGear
  id: PirateEvaCutlassGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitPirate
    shoes: ClothingShoesBootsLaceup
    head: ClothingHeadHelmetHardsuitPirateEVA
    outerClothing: ClothingOuterHardsuitPirateEVA
  inhand: [ Cutlass ]

- type: startingGear
  id: PirateEvaLaserCarbineGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitPirate
    shoes: ClothingShoesBootsLaceup
    head: ClothingHeadHelmetHardsuitPirateEVA
    outerClothing: ClothingOuterHardsuitPirateEVA
  inhand: [ WeaponLaserCarbine ]

- type: startingGear
  id: PirateCaptainLaserCarbineGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitPirate
    shoes: ClothingShoesBootsLaceup
    head: ClothingHeadBandRed
    outerClothing: ClothingOuterHardsuitPirateCap
  inhand: [ WeaponLaserCarbine, EnergyCutlass ]

- type: startingGear
  id: PirateCutlassGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitPirate
    shoes: ClothingShoesBootsLaceup
    head: ClothingHeadBandRed
  inhand: [ Cutlass ]

- type: startingGear
  id: PirateFlintlockGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitPirate
    shoes: ClothingShoesBootsLaceup
    head: ClothingHeadBandRed
    neck: ClothingNeckCloakPirateCap
    outerClothing: ClothingOuterCoatPirate
  inhand: [ WeaponPistolFlintlock ]
