- type: job
  id: Roboticist
  name: job-name-roboticist
  description: job-description-roboticist
  playTimeTracker: JobRoboticist
  requirements:
  - !type:DepartmentTimeRequirement
    department: Science
    time: 4h
  startingGear: RoboticistGear
  icon: JobIconRoboticist
  supervisors: job-supervisors-rd
  guides: [ Robotics ]
  contracts:
  - DocumentContractEmploymentRnd
  access:
  - Research
  - Maintenance
  - Robotics

- type: startingGear
  id: RoboticistGear
  equipment:
    ears: ClothingHeadsetRobotics

- type: chameleonOutfit
  id: RoboticistChameleonOutfit
  job: Roboticist
  equipment:
    head: ClothingHeadBandSkull
    eyes: ClothingEyesGlassesCheapSunglasses
    mask: ClothingMaskGas
    tie: ClothingNeckTieSci
    outerClothing: ClothingOuterCoatRobo
    gloves: ClothingHandsGlovesRobohands
    ears: ClothingHeadsetRobotics
    jumpsuit: ClothingUniformJumpsuitRoboticist
    shoes: ClothingShoesColorBlack
    id: RoboticistPDA
