// Space Onyx
// Copyright (C) 2026 Space Onyx contributors
//
// This file is licensed under AGPL-3.0-or-later.
// See LICENSES for the full license text.

using Content.Client.UserInterface.Controls;
using Content.Shared._Onyx.Radio;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Onyx.Radio.Ui;

[GenerateTypedNameReferences]
public sealed partial class HandheldRadioMenu : FancyWindow
{
    public event Action<float>? OnFrequencyEntered;
    public event Action<int>? OnFrequencyStepped;
    public event Action<bool>? OnMicPressed;
    public event Action<bool>? OnSpeakerPressed;

    public HandheldRadioMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        MinusButton.OnPressed += _ => OnFrequencyStepped?.Invoke(-1);
        PlusButton.OnPressed += _ => OnFrequencyStepped?.Invoke(1);
        FrequencyEdit.OnTextEntered += args =>
        {
            if (float.TryParse(args.Text, out var frequency))
                OnFrequencyEntered?.Invoke(frequency);
        };

        MicButton.OnPressed += args => OnMicPressed?.Invoke(args.Button.Pressed);
        SpeakerButton.OnPressed += args => OnSpeakerPressed?.Invoke(args.Button.Pressed);
    }

    public void UpdateState(HandheldRadioBuiState state)
    {
        FrequencyEdit.Text = state.Frequency.ToString("0.0");
        FrequencyEdit.Editable = !state.FrequencyLocked;
        MinusButton.Disabled = state.FrequencyLocked;
        PlusButton.Disabled = state.FrequencyLocked;

        if (state.CurrentChannelName != null)
        {
            ChannelLabel.Text = $"[{state.CurrentChannelName}]";
            ChannelLabel.ModulateSelfOverride = state.CurrentChannelColor != null
                ? Color.FromHex(state.CurrentChannelColor)
                : Color.LightGray;
        }
        else
        {
            ChannelLabel.Text = Loc.GetString("handheld-radio-menu-no-signal");
            ChannelLabel.ModulateSelfOverride = Color.DarkGray;
        }

        MicButton.Pressed = state.MicrophoneEnabled;
        SpeakerButton.Pressed = state.SpeakerEnabled;
    }
}
