using System.Linq;
using Content.Client.Stylesheets;
using Content.Shared._Onyx.Language;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Onyx.Language;

[GenerateTypedNameReferences]
public sealed partial class LanguageMenuWindow : DefaultWindow
{
    private readonly LanguageSystem _languages;
    private readonly IPrototypeManager _prototypes;

    public LanguageMenuWindow()
    {
        RobustXamlLoader.Load(this);
        _languages = IoCManager.Resolve<IEntitySystemManager>().GetEntitySystem<LanguageSystem>();
        _prototypes = IoCManager.Resolve<IPrototypeManager>();
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();
        _languages.LanguagesChanged += UpdateState;
    }

    protected override void ExitedTree()
    {
        _languages.LanguagesChanged -= UpdateState;
        base.ExitedTree();
    }

    protected override void Opened()
    {
        UpdateState();
    }

    private void UpdateState()
    {
        var speaker = _languages.GetLocalSpeaker();
        if (speaker == null)
            return;

        CurrentLanguageLabel.Text = speaker.SpokenLanguages.Count == 0
            ? Loc.GetString("language-menu-no-spoken-language")
            : _prototypes.Index(speaker.CurrentLanguage).Name;
        OptionsList.RemoveAllChildren();

        var understoodLanguages = _prototypes.EnumeratePrototypes<LanguagePrototype>()
            .Where(language => language.ShowInLanguageMenu &&
                (speaker.UnderstandsAllLanguages || language.AlwaysUnderstood))
            .Select(language => new ProtoId<LanguagePrototype>(language.ID))
            .Concat(speaker.UnderstoodLanguages);

        var knownLanguages = speaker.SpokenLanguages.Union(understoodLanguages)
            .Where(id => _prototypes.Index(id).ShowInLanguageMenu)
            .OrderBy(id => _prototypes.Index(id).Name)
            .ToArray();
        NoLanguagesLabel.Visible = knownLanguages.Length == 0;

        foreach (var id in knownLanguages)
        {
            var language = _prototypes.Index(id);
            var canSpeak = speaker.SpokenLanguages.Contains(id);
            var canUnderstand = speaker.UnderstandsAllLanguages || language.AlwaysUnderstood || speaker.UnderstoodLanguages.Contains(id);

            var row = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal };
            row.AddChild(new Label
            {
                Text = language.Name,
                HorizontalExpand = true,
                StyleClasses = { StyleClass.LabelHeading },
            });

            if (canSpeak)
            {
                var button = new Button
                {
                    Text = Loc.GetString(id == speaker.CurrentLanguage
                        ? "language-menu-selected"
                        : "language-menu-select"),
                    Disabled = id == speaker.CurrentLanguage,
                };
                button.OnPressed += _ => _languages.SelectLanguage(id);
                row.AddChild(button);
            }

            var entry = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical };
            entry.AddChild(row);
            var statusRow = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                SeparationOverride = 12,
            };
            statusRow.AddChild(CreateStatusLabel("language-menu-speaking", canSpeak));
            statusRow.AddChild(CreateStatusLabel("language-menu-understanding", canUnderstand));
            entry.AddChild(statusRow);

            var body = new CollapsibleBody
            {
                HorizontalExpand = true,
                Margin = new Thickness(4f, 4f),
            };
            var description = new RichTextLabel { HorizontalExpand = true };
            description.SetMessage(language.Description);
            body.AddChild(description);
            entry.AddChild(new Collapsible(Loc.GetString("language-menu-description-header"), body)
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                HorizontalExpand = true,
            });

            var panel = new PanelContainer { Margin = new Thickness(0f, 0f, 4f, 0f) };
            panel.StyleClasses.Add("PdaBorderRect");
            panel.AddChild(entry);
            OptionsList.AddChild(panel);
        }
    }

    private static Label CreateStatusLabel(string key, bool available)
    {
        return new Label
        {
            Text = Loc.GetString(key, ("available", available)),
            StyleClasses =
            {
                StyleClass.LabelSubText,
                available ? StyleClass.Positive : StyleClass.Negative,
            },
        };
    }
}
