# Space Onyx
# Copyright (C) 2026 Space Onyx contributors
#
# This file is licensed under AGPL-3.0-or-later.
# See LICENSES for the full license text.

- type: job
  id: HotelStaff
  name: job-name-hotel-staff
  description: job-description-hotel-staff
  playTimeTracker: JobHotelStaff
  supervisors: job-supervisors-hotel-manager
  setPreference: false
  showInLoadout: true
  icon: JobIconHotelStaff
  canBeAntag: false
  access:
  - HotelStaff
  - External

- type: job
  id: HotelSecurity
  name: job-name-hotel-secure
  description: job-description-hotel-secure
  playTimeTracker: JobHotelSecurity
  supervisors: job-supervisors-hotel-manager
  setPreference: false
  showInLoadout: true
  icon: JobIconHotelSecure
  canBeAntag: false
  access:
  - HotelSecure
  - HotelStaff
  - External
  requirements:
  - !type:RoleTimeRequirement
    role: JobHotelStaff
    time: 2h

- type: job
  id: HotelManager
  name: job-name-hotel-manager
  description: job-description-hotel-manager
  playTimeTracker: JobHotelManager
  supervisors: job-supervisors-centcom
  setPreference: false
  showInLoadout: true
  icon: JobIconHotelManager
  canBeAntag: false
  access:
  - HotelManager
  - HotelSecure
  - HotelStaff
  - External
  requirements:
  - !type:RoleTimeRequirement
    role: JobHotelStaff
    time: 7h
