using System.Linq;
using Content.Shared._Onyx.Cybernetics.Personalization;
using Content.Shared.Body.Part;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._Onyx.Cybernetics.Personalization;

[GenerateTypedNameReferences]
public sealed partial class CyberneticsPicker : BoxContainer
{
    [Dependency] private IPrototypeManager _prototypes = default!;
    [Dependency] private IEntityManager _entities = default!;

    private readonly SpriteSystem _sprites;
    private List<EntProtoId> _selected = [];
    private int _capacity;
    private PartCategory _category;
    private sealed record PickerEntry(EntProtoId Id, bool Removable, int Cost, IReadOnlyList<EntProtoId> Dependencies);

    private enum PartCategory
    {
        All,
        Arms,
        Hands,
        Legs,
        Feet,
    }

    public event Action<List<EntProtoId>>? SelectionChanged;

    public CyberneticsPicker()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _sprites = _entities.System<SpriteSystem>();

        foreach (var category in Enum.GetValues<PartCategory>())
        {
            CategoryButton.AddItem(
                Loc.GetString($"cybernetics-personalization-category-{category.ToString().ToLowerInvariant()}"),
                (int) category);
        }
        CategoryButton.SelectId((int) PartCategory.All);
        CategoryButton.OnItemSelected += args =>
        {
            CategoryButton.SelectId(args.Id);
            _category = (PartCategory) args.Id;
            Refresh();
        };
        SearchBar.OnTextChanged += _ => Refresh();
        ClearSearchButton.OnPressed += _ => SearchBar.Text = string.Empty;

        AvailableList.OnItemSelected += args =>
        {
            InstalledList.ClearSelected();
            InstallButton.Disabled = args.ItemList[args.ItemIndex].Metadata is not PickerEntry;
            RemoveButton.Disabled = true;
            UpdateDetails(args.ItemList[args.ItemIndex].Metadata as PickerEntry, false);
        };
        InstalledList.OnItemSelected += args =>
        {
            AvailableList.ClearSelected();
            InstallButton.Disabled = true;
            var entry = args.ItemList[args.ItemIndex].Metadata as PickerEntry;
            RemoveButton.Disabled = entry is not { Removable: true };
            UpdateDetails(entry, true);
        };
        InstallButton.OnPressed += _ => Install();
        RemoveButton.OnPressed += _ => Remove();
    }

    public IReadOnlyList<EntProtoId> SetData(IEnumerable<EntProtoId> selected, int capacity)
    {
        _capacity = Math.Max(0, capacity);
        _selected = RoundstartCyberneticsResolver.Normalize(
            selected,
            _capacity,
            _prototypes,
            _entities.ComponentFactory);
        Refresh();
        return _selected;
    }

    private void Install()
    {
        if (AvailableList.GetSelected().FirstOrDefault() is not { Metadata: PickerEntry entry })
            return;

        var updated = RoundstartCyberneticsResolver.Normalize(
            _selected.Append(entry.Id),
            _capacity,
            _prototypes,
            _entities.ComponentFactory);
        if (updated.Count == _selected.Count)
            return;

        _selected = updated;
        SelectionChanged?.Invoke([.. _selected]);
        Refresh();
    }

    private void Remove()
    {
        if (InstalledList.GetSelected().FirstOrDefault() is not { Metadata: PickerEntry { Removable: true } entry })
            return;

        _selected.Remove(entry.Id);
        SelectionChanged?.Invoke([.. _selected]);
        Refresh();
    }

    private void Refresh()
    {
        AvailableList.Clear();
        InstalledList.Clear();
        InstallButton.Disabled = true;
        RemoveButton.Disabled = true;
        UpdateDetails(null, false);

        RoundstartCyberneticsResolver.TryResolve(
            _selected,
            _prototypes,
            _entities.ComponentFactory,
            out var installed,
            out var used);
        var installedSet = installed.ToHashSet();

        var availableCount = 0;
        foreach (var id in RoundstartCyberneticsResolver.GetSelectable(_prototypes, _entities.ComponentFactory))
        {
            if (installedSet.Contains(id) || !MatchesFilter(id))
                continue;

            RoundstartCyberneticsResolver.TryResolve(
                [id],
                _prototypes,
                _entities.ComponentFactory,
                out var package,
                out var packageCost);
            var candidate = RoundstartCyberneticsResolver.Normalize(
                _selected.Append(id),
                _capacity,
                _prototypes,
                _entities.ComponentFactory);
            var proto = _prototypes.Index(id);
            var dependencies = package.Where(part => part != id).ToArray();
            var entry = new PickerEntry(id, true, packageCost, dependencies);
            var item = AvailableList.AddItem(
                Loc.GetString("cybernetics-personalization-entry", ("name", proto.Name), ("cost", packageCost)),
                _sprites.Frame0(new SpriteSpecifier.EntityPrototype(id)),
                metadata: entry,
                iconScale: 1.5f);
            item.Disabled = candidate.Count == _selected.Count;
            item.TooltipText = item.Disabled
                ? Loc.GetString("cybernetics-personalization-insufficient-points")
                : proto.Description;
            availableCount++;
        }

        var installedCount = 0;
        foreach (var id in installed)
        {
            if (!MatchesFilter(id))
                continue;

            var proto = _prototypes.Index(id);
            var root = _selected.Contains(id);
            var name = root
                ? proto.Name
                : Loc.GetString("cybernetics-personalization-required", ("name", proto.Name));
            RoundstartCyberneticsResolver.TryResolve(
                [id],
                _prototypes,
                _entities.ComponentFactory,
                out var package,
                out var partCost);
            var entry = new PickerEntry(id, root, partCost, package.Where(part => part != id).ToArray());
            var item = InstalledList.AddItem(
                name,
                _sprites.Frame0(new SpriteSpecifier.EntityPrototype(id)),
                metadata: entry,
                iconScale: 1.5f);
            item.TooltipText = root ? proto.Description : Loc.GetString("cybernetics-personalization-required-tooltip");
            installedCount++;
        }

        if (availableCount == 0)
            AvailableList.AddItem(Loc.GetString("cybernetics-personalization-none-available"), selectable: false);
        if (installedCount == 0)
            InstalledList.AddItem(Loc.GetString("cybernetics-personalization-none-installed"), selectable: false);

        PointsLabel.Text = Loc.GetString(
            "cybernetics-personalization-points",
            ("remaining", _capacity - used),
            ("total", _capacity));
        CapacityBar.Value = _capacity == 0 ? 0 : (float) used / _capacity;
        CapacityBar.ForegroundStyleBoxOverride = new StyleBoxFlat
        {
            BackgroundColor = used >= _capacity && _capacity > 0
                ? Color.FromHex("#D46A6A")
                : Color.FromHex("#62A7D8"),
        };
        PointsLabel.Modulate = used >= _capacity && _capacity > 0
            ? Color.FromHex("#FFB3B3")
            : Color.White;
        AvailableCountLabel.Text = Loc.GetString("cybernetics-personalization-count", ("count", availableCount));
        InstalledCountLabel.Text = Loc.GetString("cybernetics-personalization-count", ("count", installedCount));
    }

    private bool MatchesFilter(EntProtoId id)
    {
        var proto = _prototypes.Index(id);
        var search = SearchBar.Text.Trim();
        if (search.Length > 0 &&
            !proto.Name.Contains(search, StringComparison.OrdinalIgnoreCase) &&
            !proto.Description.Contains(search, StringComparison.OrdinalIgnoreCase))
            return false;

        if (_category == PartCategory.All)
            return true;

        if (!proto.TryGetComponent(out BodyPartComponent? part, _entities.ComponentFactory))
            return false;

        return _category switch
        {
            PartCategory.Arms => part.PartType == BodyPartType.Arm,
            PartCategory.Hands => part.PartType == BodyPartType.Hand,
            PartCategory.Legs => part.PartType == BodyPartType.Leg,
            PartCategory.Feet => part.PartType == BodyPartType.Foot,
            _ => true,
        };
    }

    private void UpdateDetails(PickerEntry? entry, bool installed)
    {
        if (entry == null)
        {
            DetailsIcon.Visible = false;
            DetailsTitle.Text = Loc.GetString("cybernetics-personalization-select-prompt");
            DetailsDescription.SetMessage(FormattedMessage.Empty);
            DetailsStatus.Text = Loc.GetString("cybernetics-personalization-select-hint");
            DetailsStatus.Modulate = Color.FromHex("#8F9BAA");
            return;
        }

        var proto = _prototypes.Index(entry.Id);
        DetailsIcon.Texture = _sprites.Frame0(new SpriteSpecifier.EntityPrototype(entry.Id));
        DetailsIcon.Visible = true;
        DetailsTitle.Text = proto.Name;
        DetailsDescription.SetMessage(FormattedMessage.FromUnformatted(proto.Description));

        var dependencies = entry.Dependencies.Count == 0
            ? Loc.GetString("cybernetics-personalization-no-dependencies")
            : string.Join(", ", entry.Dependencies.Select(id => _prototypes.Index(id).Name));
        DetailsStatus.Text = installed && !entry.Removable
            ? Loc.GetString("cybernetics-personalization-dependency-status")
            : Loc.GetString(
                installed ? "cybernetics-personalization-installed-status" : "cybernetics-personalization-available-status",
                ("cost", entry.Cost),
                ("dependencies", dependencies));
        DetailsStatus.Modulate = installed
            ? Color.FromHex(entry.Removable ? "#79D69B" : "#F6BE68")
            : Color.FromHex("#8BC5FF");
    }
}
