using Content.Client._Onyx.UserActions.Tabs;
using Content.Client.Stylesheets;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Network;
using Robust.Shared.Player;
using Robust.Shared.Timing;

namespace Content.Client._Onyx.UserActions;

[GenerateTypedNameReferences]
public sealed partial class UserActionsPanel : Control
{
    [Dependency] private ISharedPlayerManager _playerManager = default!;
    [Dependency] private IClientNetManager _net = default!;
    [Dependency] private IGameTiming _timing = default!;

    private EntityUid? _lastPlayer;
    private bool _initialized;
    private TimeSpan _nextPingUpdate;
    private long? _connectionId;
    private long _pingTotal;
    private int _pingSamples;

    private const int GoodPing = 100;
    private const int WarningPing = 200;

    public UserActionsPanel()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        LayoutContainer.SetAnchorPreset(TabContainer, LayoutContainer.LayoutPreset.Wide);
        LayoutContainer.SetAnchorAndMarginPreset(PingContainer, LayoutContainer.LayoutPreset.TopRight, margin: 2);
        LayoutContainer.SetMarginRight(PingContainer, -6);
        LayoutContainer.SetGrowHorizontal(PingContainer, LayoutContainer.GrowDirection.Begin);
        TabContainer.SetTabTitle(StatusTabControl, Loc.GetString("user-action-control-tab-status"));
        TabContainer.SetTabTitle(EmotesTabControl, Loc.GetString("user-action-control-tab-emote"));
        UpdatePing();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_timing.CurTime >= _nextPingUpdate)
        {
            _nextPingUpdate = _timing.CurTime + TimeSpan.FromSeconds(1);
            UpdatePing();
        }

        if (_initialized && _lastPlayer == _playerManager.LocalEntity)
            return;

        _initialized = true;
        _lastPlayer = _playerManager.LocalEntity;
        UpdateTabs();
    }

    private void UpdateTabs()
    {
        UpdateTab(StatusTabControl);
        UpdateTab(EmotesTabControl);
    }

    private void UpdateTab(BaseTabControl tab)
    {
        TabContainer.SetTabVisible(tab, tab.UpdateState());
    }

    private void UpdatePing()
    {
        PingValue.RemoveStyleClass(StyleClass.StatusGood);
        PingValue.RemoveStyleClass(StyleClass.StatusWarning);
        PingValue.RemoveStyleClass(StyleClass.StatusBad);

        if (_net.ServerChannel is not { Ping: >= 0 } channel)
        {
            _connectionId = null;
            _pingTotal = 0;
            _pingSamples = 0;
            var unavailable = Loc.GetString("user-action-control-not-available");
            PingValue.Text = Loc.GetString("user-action-control-ping-value", ("ping", unavailable));
            AveragePingValue.Text = Loc.GetString("user-action-control-average-ping-value", ("average", unavailable));
            PingValue.AddStyleClass(StyleClass.StatusBad);
            return;
        }

        if (_connectionId != channel.ConnectionId)
        {
            _connectionId = channel.ConnectionId;
            _pingTotal = 0;
            _pingSamples = 0;
        }

        var ping = channel.Ping;
        _pingTotal += ping;
        _pingSamples++;
        var average = (int) Math.Round((double) _pingTotal / _pingSamples);

        PingValue.Text = Loc.GetString("user-action-control-ping-value", ("ping", ping));
        AveragePingValue.Text = Loc.GetString("user-action-control-average-ping-value", ("average", average));
        var statusStyle = ping <= GoodPing
            ? StyleClass.StatusGood
            : ping <= WarningPing
                ? StyleClass.StatusWarning
                : StyleClass.StatusBad;
        PingValue.AddStyleClass(statusStyle);
    }
}
