using Content.Client.GameTicking;
using Content.Shared._Onyx.Time;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Timing;

namespace Content.Client._Onyx.UserActions.Tabs;

[GenerateTypedNameReferences]
public sealed partial class StatusTabControl : BaseTabControl
{
    [Dependency] private IEntityManager _entityManager = default!;
    [Dependency] private IGameTiming _gameTiming = default!;
    [Dependency] private IConfigurationManager _configuration = default!;

    private ClientGameTicker? _gameTicker;
    private TimeSpan _nextTimeUpdate;

    private const string OpenedMark = "▼";
    private const string ClosedMark = "▶";

    public StatusTabControl()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        RoundToggle.OnToggled += args => SetRoundOpen(args.Pressed);
        TimeToggle.OnToggled += args => SetTimeOpen(args.Pressed);
        SetRoundOpen(true);
        SetTimeOpen(true);
    }

    private void SetRoundOpen(bool open)
    {
        RoundToggle.Pressed = open;
        RoundChevron.Text = open ? OpenedMark : ClosedMark;
        RoundBody.Visible = open;
        RoundHeaderDivider.Visible = open;
    }

    private void SetTimeOpen(bool open)
    {
        TimeToggle.Pressed = open;
        TimeChevron.Text = open ? OpenedMark : ClosedMark;
        TimeBody.Visible = open;
        TimeHeaderDivider.Visible = open;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        var needScrollDivider = ContentBox.DesiredSize.Y > StatusScroll.Height;
        if (ScrollDivider.Visible != needScrollDivider)
            ScrollDivider.Visible = needScrollDivider;

        if (_gameTicker == null)
            return;

        if (_gameTiming.CurTime < _nextTimeUpdate)
            return;

        _nextTimeUpdate = _gameTiming.CurTime + TimeSpan.FromSeconds(1);

        var roundTime = _gameTiming.CurTime - _gameTicker.RoundStartTimeSpan;
        RoundTime.Text = roundTime > TimeSpan.Zero
            ? $"{(int) roundTime.TotalHours:00}:{roundTime.Minutes:00}:{roundTime.Seconds:00}"
            : "00:00:00";
        StationTime.Text = _gameTicker.StationDateTime.ToString("HH:mm:ss");
        CurrentDate.Text = InGameDate.At(_gameTicker.StationDateTime, _configuration).ToString("dd.MM.yyyy");
    }

    public override bool UpdateState()
    {
        if (_gameTicker == null)
        {
            _gameTicker = _entityManager.System<ClientGameTicker>();
            _gameTicker.UserActionsInfoUpdated += UpdateInfo;
        }

        UpdateInfo();
        return true;
    }

    private void UpdateInfo()
    {
        if (_gameTicker?.UserActionsInfo is not { } info)
            return;

        MapName.Text = info.MapName;
        MapName.ToolTip = info.MapName;
        RoundId.Text = info.RoundId.ToString();
        GameMode.Text = info.GameMode;
        GameMode.ToolTip = info.GameMode;
        PlayerCount.Text = info.PlayerCount.ToString();
    }

    protected override void Dispose(bool disposing)
    {
        if (_gameTicker != null)
            _gameTicker.UserActionsInfoUpdated -= UpdateInfo;

        base.Dispose(disposing);
    }
}
