using System.Linq;
using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared._Onyx.Surgery.Augments.NeuroInterface;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Onyx.Surgery.Augments.NeuroInterface;

[GenerateTypedNameReferences]
public sealed partial class NeuroInterfaceWindow : FancyWindow
{
    private static readonly Color Cyan = Color.FromHex("#9fb0c4");
    private static readonly Color Teal = Color.FromHex("#4f6074");
    private static readonly Color Active = Color.FromHex("#c6d4e5");
    private static readonly Color Inactive = Color.FromHex("#8998aa");
    private static readonly Color Positive = Color.FromHex("#8fc9a3");
    private static readonly Color Negative = Color.FromHex("#df8b8b");
    private const float TooltipTextMaxWidth = 380f;

    public event Action<NetEntity, bool>? OnEnabledChanged;

    private readonly ButtonGroup _tabGroup = new(isNoneSetAllowed: false);
    private NeuroInterfaceBuiState? _state;
    private NeuroInterfaceBodyRegion? _region;

    private enum Page : byte
    {
        Overview,
        Hardware,
    }

    public NeuroInterfaceWindow()
    {
        RobustXamlLoader.Load(this);
        ApplyPanels();

        ConfigureTab(OverviewTab, Page.Overview);
        ConfigureTab(HardwareTab, Page.Hardware);

        RegionFilter.AddItem(Loc.GetString("neuro-interface-region-all"), -1);
        foreach (var region in Enum.GetValues<NeuroInterfaceBodyRegion>())
            RegionFilter.AddItem(Loc.GetString(GetRegionKey(region)), (int) region);
        RegionFilter.SelectId(-1);
        RegionFilter.OnItemSelected += args =>
        {
            RegionFilter.SelectId(args.Id);
            _region = args.Id < 0 ? null : (NeuroInterfaceBodyRegion) args.Id;
            RebuildAugments();
        };
        SearchBar.OnTextChanged += _ => RebuildAugments();

        OverviewTab.Pressed = true;
        ShowPage(Page.Overview);
        StyleTabs();
    }

    public void UpdateState(NeuroInterfaceBuiState state)
    {
        var rebuildAugments = _state == null || !EntriesEqual(_state.Entries, state.Entries);
        _state = state;
        PowerBalanceLabel.Text = Loc.GetString("neuro-interface-power-balance",
            ("generation", MathF.Round(state.PowerGeneration, 1)),
            ("consumption", MathF.Round(state.PowerConsumption, 1)));
        PowerBalanceLabel.FontColorOverride = state.PowerGeneration < state.PowerConsumption ? Negative : Cyan;
        PowerSourceList.Children.Clear();
        if (state.PowerSources.Count == 0)
            PowerSourceList.AddChild(MutedLabel("neuro-interface-power-sources-empty"));
        else
        {
            foreach (var source in state.PowerSources)
                PowerSourceList.AddChild(new Label
                {
                    Text = Loc.GetString("neuro-interface-power-source-entry", ("source", source)),
                    ClipText = true,
                });
        }
        BatteryList.Children.Clear();
        if (state.Batteries.Count == 0)
            BatteryList.AddChild(MutedLabel("neuro-interface-batteries-empty"));
        else
        {
            foreach (var battery in state.Batteries)
            {
                var percent = battery.Capacity > 0f ? battery.Charge / battery.Capacity * 100f : 0f;
                var batteryPanel = new PanelContainer { PanelOverride = PanelStyle("#1d2631", Teal) };
                var batteryText = new BoxContainer
                {
                    Orientation = BoxContainer.LayoutOrientation.Vertical,
                    Margin = new Thickness(7, 4),
                };
                batteryText.AddChild(new Label
                {
                    Text = battery.Name,
                    FontColorOverride = Active,
                    ClipText = true,
                });
                batteryText.AddChild(new Label
                {
                    Text = Loc.GetString("neuro-interface-battery-values",
                        ("charge", MathF.Round(battery.Charge)),
                        ("capacity", MathF.Round(battery.Capacity)),
                        ("percent", MathF.Round(percent)),
                        ("rate", MathF.Round(battery.ChargeRate, 1))),
                    StyleClasses = { "font-small" },
                    FontColorOverride = Cyan,
                    ClipText = true,
                    MouseFilter = MouseFilterMode.Stop,
                    ToolTip = Loc.GetString("neuro-interface-tooltip-battery-values"),
                });
                batteryPanel.AddChild(batteryText);
                BatteryList.AddChild(batteryPanel);
            }
        }
        ExtensionList.Children.Clear();
        if (state.Modules.Count == 0)
            ExtensionList.AddChild(MutedLabel("neuro-interface-extensions-empty"));
        else
        {
            foreach (var module in state.Modules)
                ExtensionList.AddChild(new Label
                {
                    Text = Loc.GetString("neuro-interface-extension-entry", ("name", module)),
                    ClipText = true,
                });
        }

        if (rebuildAugments)
            RebuildAugments();
    }

    private void ConfigureTab(Button button, Page page)
    {
        button.Group = _tabGroup;
        StyleTab(button, false);
        button.OnPressed += _ =>
        {
            ShowPage(page);
            StyleTabs();
        };
    }

    private void ShowPage(Page page)
    {
        OverviewScreen.Visible = page == Page.Overview;
        HardwareScreen.Visible = page == Page.Hardware;
        ScreenTitle.Text = Loc.GetString(page switch
        {
            Page.Overview => "neuro-interface-nav-overview",
            _ => "neuro-interface-nav-hardware",
        });
        ScreenSubtitle.Text = Loc.GetString(page switch
        {
            Page.Overview => "neuro-interface-overview-subtitle",
            _ => "neuro-interface-hardware-subtitle",
        });
        if (page == Page.Overview)
            RebuildAugments();
    }

    private void RebuildAugments()
    {
        if (_state == null)
            return;

        EntryList.Children.Clear();
        var search = SearchBar.Text.Trim();
        var entriesByParent = new Dictionary<NetEntity, List<NeuroInterfaceEntryData>>();
        foreach (var entry in _state.Entries)
        {
            if (entry.Parent is not { } parent)
                continue;

            if (!entriesByParent.TryGetValue(parent, out var children))
            {
                children = new List<NeuroInterfaceEntryData>();
                entriesByParent.Add(parent, children);
            }
            children.Add(entry);
        }
        var filtered = _state.Entries
            .Where(entry => entry.Parent == null && (_region == null || entry.Region == _region))
            .Where(entry => search.Length == 0 || TreeContains(entry, entriesByParent, search))
            .OrderBy(entry => entry.Name, StringComparer.OrdinalIgnoreCase)
            .ToList();
        var count = filtered.Count;
        AugmentCount.Text = Loc.GetString("neuro-interface-augment-count", ("count", count));

        foreach (var group in filtered.GroupBy(entry => entry.Region).OrderBy(group => group.Key))
        {
            EntryList.AddChild(CreateGroupHeader(group.Key, group.Count()));
            foreach (var entry in group)
                AddEntryTree(entry, entriesByParent, search, 0);
        }

        if (count == 0)
            EntryList.AddChild(MutedLabel("neuro-interface-augments-empty"));
    }

    private void AddEntryTree(
        NeuroInterfaceEntryData entry,
        Dictionary<NetEntity, List<NeuroInterfaceEntryData>> entriesByParent,
        string search,
        int depth)
    {
        EntryList.AddChild(CreateEntry(entry, depth));
        if (!entriesByParent.TryGetValue(entry.Entity, out var children))
            return;

        foreach (var child in children
                     .Where(child => search.Length == 0 || TreeContains(child, entriesByParent, search))
                     .OrderBy(child => child.Name, StringComparer.OrdinalIgnoreCase))
            AddEntryTree(child, entriesByParent, search, depth + 1);
    }

    private static bool TreeContains(
        NeuroInterfaceEntryData entry,
        Dictionary<NetEntity, List<NeuroInterfaceEntryData>> entriesByParent,
        string search)
    {
        if (entry.Name.Contains(search, StringComparison.OrdinalIgnoreCase))
            return true;

        return entriesByParent.TryGetValue(entry.Entity, out var children) &&
            children.Any(child => TreeContains(child, entriesByParent, search));
    }

    private Control CreateGroupHeader(NeuroInterfaceBodyRegion region, int count)
    {
        var text = Loc.GetString("neuro-interface-region-header",
            ("region", Loc.GetString(GetRegionKey(region))), ("count", count));
        return CreateHeader(text);
    }

    private Control CreateHeader(string text)
    {
        var panel = new PanelContainer { PanelOverride = PanelStyle("#0b292d", Teal) };
        panel.AddChild(new Label
        {
            Text = text,
            Margin = new Thickness(8, 4),
            FontColorOverride = Active,
        });
        return panel;
    }

    private Control CreateEntry(NeuroInterfaceEntryData entry, int depth)
    {
        var statusColor = GetStatusColor(entry.Status);
        var panel = new PanelContainer
        {
            PanelOverride = PanelStyle(entry.Enabled ? "#18333a" : "#222c38", statusColor),
        };
        var card = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            SeparationOverride = 6,
            Margin = new Thickness(9 + depth * 18, 7, 9, 7),
        };
        var header = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            SeparationOverride = 8,
        };
        var status = new Label
        {
            Text = Loc.GetString(GetStatusKey(entry.Status)),
            MinWidth = 90,
            MaxWidth = 90,
            VerticalAlignment = VAlignment.Center,
            Align = Label.AlignMode.Center,
            FontColorOverride = statusColor,
            ClipText = true,
            MouseFilter = MouseFilterMode.Stop,
        };
        var name = new Label
        {
            Text = depth > 0 ? $"└ {entry.Name}" : entry.Name,
            MinWidth = 160,
            HorizontalExpand = true,
            VerticalAlignment = VAlignment.Center,
            ClipText = true,
            FontColorOverride = entry.Enabled ? Active : Inactive,
        };
        var info = CreateButton("?", 30);
        info.SetWidth = 30;
        info.SetHeight = 30;
        info.TooltipSupplier = _ => BuildAugmentTooltip(entry, statusColor);

        Button? toggle = null;
        if (entry.CanToggle)
        {
            toggle = CreateButton(Loc.GetString(entry.Enabled
                ? "neuro-interface-button-disable"
                : "neuro-interface-button-enable"), 92);
            StyleButton(toggle, entry.Enabled);
            toggle.OnPressed += _ => OnEnabledChanged?.Invoke(entry.Entity, !entry.Enabled);
        }
        header.AddChild(info);
        header.AddChild(name);
        header.AddChild(status);
        if (toggle != null)
            header.AddChild(toggle);
        card.AddChild(header);
        panel.AddChild(card);
        return panel;
    }

    private Control BuildAugmentTooltip(NeuroInterfaceEntryData entry, Color statusColor)
    {
        var content = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            SeparationOverride = 5,
            Margin = new Thickness(10, 8),
        };
        if (!string.IsNullOrWhiteSpace(entry.Description))
            AddTooltipText(content, entry.Description, Color.White);

        if (entry.Power > 0f)
            AddTooltipSection(content, Loc.GetString("neuro-interface-tooltip-section-resources"),
                [Loc.GetString("neuro-interface-tooltip-resource-power", ("value", entry.Power))]);
        foreach (var section in entry.TooltipSections)
            AddTooltipSection(content, section.Title, section.Lines);

        var panel = new PanelContainer
        {
            PanelOverride = PanelStyle("#1b2530", statusColor, 2),
        };
        panel.AddChild(content);
        return panel;
    }

    private static void AddTooltipSection(BoxContainer content, string title, IReadOnlyList<string> lines)
    {
        if (lines.Count == 0)
            return;

        AddTooltipText(content, title, Cyan, new Thickness(0, 4, 0, 0));
        foreach (var line in lines)
            AddTooltipText(content, line, Color.White, new Thickness(8, 0, 0, 0));
    }

    private static void AddTooltipText(BoxContainer content, string text, Color color, Thickness? margin = null)
    {
        var label = new RichTextLabel
        {
            MaxWidth = TooltipTextMaxWidth,
            HorizontalExpand = true,
            Margin = margin ?? new Thickness(0),
        };
        label.SetMessage(FormattedMessage.FromUnformatted(text), defaultColor: color);
        content.AddChild(label);
    }

    private void ApplyPanels()
    {
        MainFrame.PanelOverride = PanelStyle("#12171e", Teal, 2);
        TabRail.PanelOverride = PanelStyle("#151d27", Teal);
        ContentPanel.PanelOverride = PanelStyle("#171d25", Teal);
        Divider.PanelOverride = PanelStyle("#4f6074", Teal);
        PowerPanel.PanelOverride = PanelStyle("#161e28", Teal);
        AugmentsPanel.PanelOverride = PanelStyle("#121a23", Teal);
        ExtensionsPanel.PanelOverride = PanelStyle("#161e28", Teal);
    }

    private void StyleTabs()
    {
        StyleTab(OverviewTab, OverviewTab.Pressed);
        StyleTab(HardwareTab, HardwareTab.Pressed);
    }

    private static void StyleTab(Button button, bool selected)
    {
        button.StyleBoxOverride = new StyleBoxFlat
        {
            BackgroundColor = Color.FromHex(selected ? "#426b57" : "#536b83"),
            BorderColor = selected ? Color.FromHex("#9ed0ae") : Color.FromHex("#91a8bf"),
            BorderThickness = new Thickness(selected ? 2 : 1),
            ContentMarginLeftOverride = 8,
            ContentMarginRightOverride = 8,
            ContentMarginTopOverride = 6,
            ContentMarginBottomOverride = 6,
        };
        button.Label.FontColorOverride = selected ? Color.FromHex("#e5fcff") : Color.FromHex("#dce8f5");
        button.Label.Align = Label.AlignMode.Center;
    }

    private static Button CreateButton(string text, float minWidth)
    {
        var button = new Button
        {
            Text = text,
            MinWidth = minWidth,
            MinHeight = 30,
        };
        StyleButton(button, false);
        return button;
    }

    private static void StyleButton(Button button, bool selected, bool disabled = false)
    {
        button.StyleBoxOverride = new StyleBoxFlat
        {
            BackgroundColor = Color.FromHex(disabled ? "#344352" : selected ? "#4f775f" : "#647b94"),
            BorderColor = disabled ? Color.FromHex("#647486") : selected ? Color.FromHex("#a7d7b5") : Color.FromHex("#a8bbce"),
            BorderThickness = new Thickness(selected ? 2 : 1),
            ContentMarginLeftOverride = 6,
            ContentMarginRightOverride = 6,
            ContentMarginTopOverride = 4,
            ContentMarginBottomOverride = 4,
        };
        button.Label.FontColorOverride = disabled ? Inactive : Color.FromHex("#f4f8fc");
    }

    private static Label MutedLabel(string key) => new()
    {
        Text = Loc.GetString(key),
        FontColorOverride = Inactive,
        HorizontalAlignment = HAlignment.Center,
        Margin = new Thickness(0, 12),
    };

    private static string GetRegionKey(NeuroInterfaceBodyRegion region) =>
        $"neuro-interface-region-{region.ToString().ToLowerInvariant()}";

    private static string GetStatusKey(NeuroConsumerStatus status) => status switch
    {
        NeuroConsumerStatus.Disabled => "neuro-interface-ui-status-disabled",
        NeuroConsumerStatus.Full => "neuro-interface-ui-status-online",
        NeuroConsumerStatus.Emp => "neuro-interface-ui-status-emp",
        _ => "neuro-interface-ui-status-disabled",
    };

    private static Color GetStatusColor(NeuroConsumerStatus status) => status switch
    {
        NeuroConsumerStatus.Full => Positive,
        NeuroConsumerStatus.Emp => Negative,
        _ => Inactive,
    };

    private static bool EntriesEqual(List<NeuroInterfaceEntryData> left, List<NeuroInterfaceEntryData> right)
    {
        if (left.Count != right.Count)
            return false;

        var rightByEntity = right.ToDictionary(entry => entry.Entity);
        foreach (var a in left)
        {
            if (!rightByEntity.TryGetValue(a.Entity, out var b) ||
                a.Name != b.Name || a.Parent != b.Parent || a.Power != b.Power ||
                a.Description != b.Description ||
                a.Enabled != b.Enabled || a.Status != b.Status || a.Region != b.Region ||
                a.CanToggle != b.CanToggle ||
                !TooltipSectionsEqual(a.TooltipSections, b.TooltipSections))
                return false;
        }
        return true;
    }

    private static bool TooltipSectionsEqual(
        List<NeuroInterfaceTooltipSectionData> left,
        List<NeuroInterfaceTooltipSectionData> right)
    {
        if (left.Count != right.Count)
            return false;

        for (var i = 0; i < left.Count; i++)
        {
            if (left[i].Id != right[i].Id || left[i].Title != right[i].Title ||
                !left[i].Lines.SequenceEqual(right[i].Lines))
                return false;
        }

        return true;
    }

    private static StyleBoxFlat PanelStyle(string background, Color border, int thickness = 1) => new()
    {
        BackgroundColor = Color.FromHex(background),
        BorderColor = border,
        BorderThickness = new Thickness(thickness),
    };
}
