using System;
using Content.Client._Onyx.Discord;
using Content.Client.Administration.UI.CustomControls;
using Content.Client.Info;
using Content.Client.Message;
using Content.Client.UserInterface.Systems.EscapeMenu;
using Content.Shared.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;

namespace Content.Client.Lobby.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class LobbyGui : UIScreen
    {
        [Dependency] private IClientConsoleHost _consoleHost = default!;
        [Dependency] private DiscordIdManager _discordIdManager = default!;
        [Dependency] private IConfigurationManager _cfg = default!;
        public LobbyGui()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);
            SetAnchorPreset(MainContainer, LayoutPreset.Wide);
            SetAnchorPreset(Background, LayoutPreset.Wide);

            LobbySong.SetMarkup(Loc.GetString("lobby-state-song-no-song-text"));
            LobbyBackground.SetMarkup(Loc.GetString("lobby-state-background-no-background-text"));

            LeaveButton.OnPressed += _ => _consoleHost.ExecuteCommand("disconnect");
            OptionsButton.OnPressed += _ => UserInterfaceManager.GetUIController<OptionsUIController>().ToggleWindow();

            CollapseButton.OnPressed += _ => TogglePanel(false);
            ExpandButton.OnPressed += _ => TogglePanel(true);
            // <Onyx-Lobby>
            LeftCollapseButton.OnPressed += _ => ToggleLeftPanel(false);
            LeftExpandButton.OnPressed += _ => ToggleLeftPanel(true);

            TopCollapseButton.OnPressed += _ => ToggleTopPanel(false);
            TopExpandButton.OnPressed += _ => ToggleTopPanel(true);

            AttributionCollapseButton.OnPressed += _ => ToggleAttributionPanel(false);
            AttributionExpandButton.OnPressed += _ => ToggleAttributionPanel(true);
            // </Onyx-Lobby>
            _discordIdManager.DiscordInfoUpdated += UpdateDiscordButtonState;
            _cfg.OnValueChanged(CCVars.DiscordAuthEnable, OnDiscordAuthEnableChanged, true);
        }

        private void OnDiscordAuthEnableChanged(bool enabled)
        {
            DiscordLinkButton.Visible = enabled;
            if (enabled)
                _discordIdManager.RequestDiscordInfo();
            else
                _discordIdManager.Clear();
        }

        private void UpdateDiscordButtonState()
        {
            var linked = _discordIdManager.TryGetDiscordId(out _);
            DiscordLinkButton.ModulateSelfOverride = linked ? Color.FromHex("#5DA130") : Color.FromHex("#AB3232");
            DiscordLinkButton.Text = Loc.GetString(linked
                ? "ui-lobby-discord-menu-link"
                : "ui-lobby-discord-menu-make-link");
        }

        public void SwitchState(LobbyGuiState state)
        {
            DefaultState.Visible = false;
            CharacterSetupState.Visible = false;

            switch (state)
            {
                case LobbyGuiState.Default:
                    DefaultState.Visible = true;
                    RightSide.Visible = true;
                    // <Onyx-Lobby>
                    LeftSide.HorizontalExpand = false;
                    LayoutSpacer.Visible = true;
                    ExpandPanel.Visible = false;
                    TopPanel.Visible = true;
                    TopExpandPanel.Visible = false;
                    LeftInfoPanel.Visible = true;
                    LeftExpandPanel.Visible = false;
                    AttributionPanel.Visible = false;
                    AttributionExpandPanel.Visible = true;
                    // </Onyx-Lobby>
                    break;
                case LobbyGuiState.CharacterSetup:
                    CharacterSetupState.Visible = true;

                    // <Onyx-Lobby>
                    LeftSide.HorizontalExpand = true;
                    LayoutSpacer.Visible = false;
                    RightSide.Visible = false;
                    // </Onyx-Lobby>

                    UserInterfaceManager.GetUIController<LobbyUIController>().ReloadCharacterSetup();
                    break;
            }
        }
        private void TogglePanel(bool value)
        {
            RightSide.Visible = value;
            ExpandPanel.Visible = !value;
        }
        // <Onyx-Lobby>
        private void ToggleLeftPanel(bool value)
        {
            LeftInfoPanel.Visible = value;
            LeftExpandPanel.Visible = !value;
        }

        private void ToggleTopPanel(bool value)
        {
            TopPanel.Visible = value;
            TopExpandPanel.Visible = !value;
        }

        private void ToggleAttributionPanel(bool value)
        {
            AttributionPanel.Visible = value;
            AttributionExpandPanel.Visible = !value;
        }
        // </Onyx-Lobby>

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _discordIdManager.DiscordInfoUpdated -= UpdateDiscordButtonState;
                _cfg.UnsubValueChanged(CCVars.DiscordAuthEnable, OnDiscordAuthEnableChanged);
            }
            base.Dispose(disposing);
        }

        public enum LobbyGuiState : byte
        {
            /// <summary>
            ///  The default state, i.e., what's seen on launch.
            /// </summary>
            Default,
            /// <summary>
            ///  The character setup state.
            /// </summary>
            CharacterSetup
        }
    }
}
