- type: playTimeTracker
  id: JobRoboticist

- type: playTimeTracker
  id: JobSurgeon

- type: playTimeTracker
  id: JobBlueshieldOfficer

- type: playTimeTracker
  id: JobVirologist

# SPDX-FileCopyrightText: 2024 Aidenkrz <aiden@djkraz.com>
# SPDX-FileCopyrightText: 2024 Piras314 <p1r4s@proton.me>
# SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

- type: playTimeTracker
  id: JobRadioHost

- type: playTimeTracker
  id: JobShaftMiner

- type: playTimeTracker
  id: JobBitrunner

- type: playTimeTracker
  id: JobBitrunAvatar


# Content below taken from Wega (https://github.com/wega-team/ss14-wega), licensed under GNU GPL v3.
- type: playTimeTracker
  id: JobGeneticist

# Space Onyx
# Copyright (C) 2026 Space Onyx contributors
#
# This file is licensed under AGPL-3.0-or-later.
# See LICENSES for the full license text.
- type: playTimeTracker
  id: JobHotelStaff

- type: playTimeTracker
  id: JobHotelSecurity

- type: playTimeTracker
  id: JobHotelManager
