using System.Linq;
using System.Numerics;
// <Onyx-HealthAnalyzer-StatusDoll>
using Content.Shared._Onyx.Targeting;
using Content.Shared._Onyx.Medical;
using Content.Shared._Onyx.Wounds;
using Content.Shared.Damage;
using Content.Client._Onyx.Medical.HealthAnalyzer;
// </Onyx-HealthAnalyzer-StatusDoll>
using Content.Shared.Atmos;
using Content.Shared.Damage.Components;
using Content.Shared.Damage.Prototypes;
using Content.Shared.Damage.Systems;
using Content.Shared.Chemistry.Reagent; // <Onyx-HealthAnalyzerChemicals>
using Content.Shared.FixedPoint;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Prototypes;
using Content.Shared.IdentityManagement;
using Content.Shared.MedicalScanner;
using Content.Shared.Mobs;
using Content.Shared.Mobs.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;
namespace Content.Client.HealthAnalyzer.UI;

// Health analyzer UI is split from its window because it's used by both the
// health analyzer item and the cryo pod UI.

[GenerateTypedNameReferences]
public sealed partial class HealthAnalyzerControl : BoxContainer
{
    private const float DangerousBloodLevel = 0.65f;

    private readonly IEntityManager _entityManager;
    private readonly SpriteSystem _spriteSystem;
    private readonly IPrototypeManager _prototypes;
    private readonly IResourceCache _cache;
    private readonly DamageableSystem _damageable;
    public bool IsHumanoid { get; private set; } // <Onyx-HealthAnalyzer-Interface>
    // <Onyx-HealthAnalyzer-StatusDoll>
    private HealthAnalyzerUiState _state;
    private NetEntity? _displayedTarget;
    private TargetBodyPart? _selectedPart;
    private EntityUid? _target;
    // <Onyx-HealthAnalyzerOrgans>
    private readonly Dictionary<NetEntity, (BoxContainer Row, EllipsisLabel Name, Label Health)> _organRows = new();
    private bool _organsUnavailable;
    // </Onyx-HealthAnalyzerOrgans>
    // </Onyx-HealthAnalyzer-StatusDoll>

    public HealthAnalyzerControl()
    {
        RobustXamlLoader.Load(this);

        var dependencies = IoCManager.Instance!;
        _entityManager = dependencies.Resolve<IEntityManager>();
        _spriteSystem = _entityManager.System<SpriteSystem>();
        _prototypes = dependencies.Resolve<IPrototypeManager>();
        _cache = dependencies.Resolve<IResourceCache>();
        _damageable = _entityManager.System<DamageableSystem>();
        // <Onyx-HealthAnalyzer-StatusDoll>
        StatusDoll.PartSelected += OnPartSelected;
        WholeBodyButton.OnPressed += _ => SelectPart(null);
        // </Onyx-HealthAnalyzer-StatusDoll>
    }

    public void Populate(HealthAnalyzerUiState state)
    {
        var target = _entityManager.GetEntity(state.TargetEntity);

        if (target == null
            || !_entityManager.HasComponent<DamageableComponent>(target))
        {
            NoPatientDataPanel.Visible = true; // <Onyx-HealthAnalyzer-Interface-edited>
            // <Onyx-HealthAnalyzer-StatusDoll-edited>
            PatientDataContainer.Visible = false;
            DiagnosticColumns.Visible = false;
            AlertsDivider.Visible = false;
            AlertsContainer.Visible = false;
            GroupsContainer.RemoveAllChildren();
            ClearOrganRows(); // <Onyx-HealthAnalyzerOrgans-edited>
            ChemicalsContainer.RemoveAllChildren(); // <Onyx-HealthAnalyzerChemicals>
            _target = null;
            _displayedTarget = null;
            _selectedPart = null;
            IsHumanoid = false; // <Onyx-HealthAnalyzer-Interface>
            // </Onyx-HealthAnalyzer-StatusDoll-edited>
            return;
        }

        NoPatientDataPanel.Visible = false; // <Onyx-HealthAnalyzer-Interface-edited>
        // <Onyx-HealthAnalyzer-StatusDoll-edited>
        PatientDataContainer.Visible = true;
        DiagnosticColumns.Visible = true;
        // </Onyx-HealthAnalyzer-StatusDoll-edited>

        // <Onyx-HealthAnalyzer-StatusDoll>
        if (_displayedTarget != state.TargetEntity)
            _selectedPart = null;
        _displayedTarget = state.TargetEntity;
        _state = state;
        _target = target;
        // <Onyx-HealthAnalyzer-Interface>
        IsHumanoid = _entityManager.HasComponent<HumanoidProfileComponent>(target.Value);
        SpeciesLabel.Visible = IsHumanoid;
        WoundDiagnosticPanel.Visible = IsHumanoid;
        // </Onyx-HealthAnalyzer-Interface>
        DrawDiseases(target.Value); // <Onyx-DiseaseHealthAnalyzer-edited>
        if (_selectedPart is { } selected && (state.PartDamage == null || !state.PartDamage.ContainsKey(selected)))
            _selectedPart = null;
        // </Onyx-HealthAnalyzer-StatusDoll>

        // Scan Mode

        ScanModeLabel.Text = state.ScanMode.HasValue
            ? state.ScanMode.Value
                ? Loc.GetString("health-analyzer-window-scan-mode-active")
                : Loc.GetString("health-analyzer-window-scan-mode-inactive")
            : Loc.GetString("health-analyzer-window-entity-unknown-text");

        ScanModeLabel.FontColorOverride = state.ScanMode.HasValue && state.ScanMode.Value ? Color.Green : Color.Red;

        // Patient Information

        // <Onyx-HealthAnalyzer-StatusDoll-edited>
        var active = state.ScanMode == true;
        var showDoll = active && IsHumanoid && state.PartDamage != null; // <Onyx-HealthAnalyzer-Interface-edited>
        SpriteView.SetEntity(target.Value);
        SpriteView.Visible = active && !showDoll;
        StatusDoll.Visible = showDoll;
        WholeBodyButton.Visible = showDoll;
        WholeBodyButton.Disabled = _selectedPart == null;
        NoDataTex.Visible = !active;
        if (showDoll)
            StatusDoll.Refresh(state.PartDamage!, _spriteSystem);
        DrawWoundDiagnostics(state);
        // <Onyx-HealthAnalyzerOrgans-edited>
        DrawOrgans(state);
        // </Onyx-HealthAnalyzerOrgans-edited>
        DrawChemicals(state); // <Onyx-HealthAnalyzerChemicals>
        // </Onyx-HealthAnalyzer-StatusDoll-edited>

        var name = new FormattedMessage();
        name.PushColor(Color.White);
        name.AddText(_entityManager.HasComponent<MetaDataComponent>(target.Value)
            ? Identity.Name(target.Value, _entityManager)
            : Loc.GetString("health-analyzer-window-entity-unknown-text"));
        NameLabel.SetMessage(name);

        SpeciesLabel.Text =
            _entityManager.TryGetComponent<HumanoidProfileComponent>(target.Value,
                out var humanoidComponent)
                ? Loc.GetString(_prototypes.Index(humanoidComponent.Species).Name)
                : Loc.GetString("health-analyzer-window-entity-unknown-species-text");

        // Basic Diagnostic

        TemperatureLabel.Text = !float.IsNaN(state.Temperature)
            ? $"{state.Temperature - Atmospherics.T0C:F1} °C ({state.Temperature:F1} K)"
            : Loc.GetString("health-analyzer-window-entity-unknown-value-text");

        BloodLabel.Text = !float.IsNaN(state.BloodLevel)
            ? $"{state.BloodLevel * 100:F1} %"
            : Loc.GetString("health-analyzer-window-entity-unknown-value-text");

        StatusLabel.Text =
            _entityManager.TryGetComponent<MobStateComponent>(target.Value, out var mobStateComponent)
                ? GetStatus(mobStateComponent.CurrentState)
                : Loc.GetString("health-analyzer-window-entity-unknown-text");

        // <Onyx-HealthAnalyzer-StatusDoll-edited>
        DrawDamage(target.Value);
        // </Onyx-HealthAnalyzer-StatusDoll-edited>
        // <Onyx-VitalDamage>
        if (state.VitalDamage is { } vitalDamage)
        {
            VitalDamageLabel.Visible = true;
            VitalDamageValueLabel.Visible = true;
            VitalDamageValueLabel.Text = vitalDamage.ToString();
        }
        else
        {
            VitalDamageLabel.Visible = false;
            VitalDamageValueLabel.Visible = false;
        }
        // </Onyx-VitalDamage>

        // Alerts

        var showAlerts = state.Unrevivable == true;

        AlertsDivider.Visible = showAlerts;
        AlertsContainer.Visible = showAlerts;

        if (showAlerts)
            AlertsContainer.RemoveAllChildren();

        if (state.Unrevivable == true)
            AlertsContainer.AddChild(new RichTextLabel
            {
                Text = Loc.GetString("health-analyzer-window-entity-unrevivable-text"),
                Margin = new Thickness(0, 4),
                MaxWidth = 300
            });

    }

    // <Onyx-HealthAnalyzer-StatusDoll>
    private void OnPartSelected(TargetBodyPart part) => SelectPart(part);

    private void SelectPart(TargetBodyPart? part)
    {
        if (_target is not { } target || _state.PartDamage == null || part is { } selected && !_state.PartDamage.ContainsKey(selected))
            return;

        _selectedPart = part;
        WholeBodyButton.Disabled = part == null;
        StatusDoll.Refresh(_state.PartDamage, _spriteSystem);
        DrawDamage(target);
    }

    private void DrawDamage(EntityUid target)
    {
        IReadOnlyDictionary<ProtoId<DamageGroupPrototype>, FixedPoint2> groups;
        IReadOnlyDictionary<ProtoId<DamageTypePrototype>, FixedPoint2> types;

        if (_selectedPart is { } selected && _state.PartDamage?.GetValueOrDefault(selected) is { } partDamage)
        {
            DamageScopeLabel.Text = Loc.GetString("health-analyzer-window-entity-damage-part-text",
                ("part", Loc.GetString($"targeting-part-{PartKey(selected)}")));
            DamageLabel.Text = partDamage.GetTotal().ToString();
            groups = partDamage.GetDamagePerGroup(_prototypes);
            types = partDamage.DamageDict;
        }
        else
        {
            DamageScopeLabel.Text = Loc.GetString("health-analyzer-window-entity-damage-total-text");
            DamageLabel.Text = _damageable.GetTotalDamage(target).ToString();
            groups = _damageable.GetDamagePerGroup(target);
            types = _damageable.GetAllDamage(target).DamageDict;
        }

        DrawDiagnosticGroups(
            groups.OrderByDescending(damage => damage.Value).ToDictionary(x => x.Key, x => x.Value),
            types);
    }

    private static string PartKey(TargetBodyPart part) => part.ToString()
        .Replace("Left", "left-")
        .Replace("Right", "right-")
        .ToLowerInvariant();

    private void DrawWoundDiagnostics(HealthAnalyzerUiState state)
    {
        WoundFindingsContainer.RemoveAllChildren();
        WoundDiagnosticStateLabel.Visible = true;

        if (state.ScanMode != true)
        {
            WoundDiagnosticStateLabel.SetMessage(Loc.GetString("health-analyzer-wound-diagnostics-inactive"));
            return;
        }

        if (IsDangerousBloodLevel(state.BloodLevel))
            AddWoundFinding(Loc.GetString("health-analyzer-wound-blood-level-dangerous"));

        if (state.WoundDiagnostics == null)
        {
            WoundDiagnosticStateLabel.SetMessage(Loc.GetString("health-analyzer-wound-diagnostics-unavailable"));
            return;
        }

        WoundDiagnosticStateLabel.Visible = false;
        foreach (var part in SharedTargetingSystem.SelectableParts)
        {
            if (!state.WoundDiagnostics.Parts.TryGetValue(part, out var diagnostic))
                continue;

            var partName = Loc.GetString($"targeting-part-{PartKey(part)}");
            var details = new List<string>();

            if (diagnostic.VisibleWounds.Count > 0)
            {
                var wounds = diagnostic.VisibleWounds.Select(wound =>
                {
                    var type = Loc.GetString(wound.Name);
                    var stage = wound.StageName is { } stageName
                        ? $" ({Loc.GetString(stageName)})"
                        : string.Empty;
                    return $"{type}{stage}{(wound.Count > 1 ? $" ×{wound.Count}" : string.Empty)}";
                });
                details.Add(string.Join(", ", wounds));
            }

            if (diagnostic.BleedingRate > 0f)
                details.Add(Loc.GetString("health-analyzer-wound-bleeding-short"));

            if (diagnostic.InternalBleedingRate > 0f)
                details.Add(Loc.GetString("health-analyzer-wound-internal-bleeding-short"));

            if (diagnostic.ClottingPhase is HealthAnalyzerClottingPhase.InProgress or HealthAnalyzerClottingPhase.Complete or HealthAnalyzerClottingPhase.Mixed)
                details.Add(Loc.GetString($"health-analyzer-wound-clotting-{diagnostic.ClottingPhase.ToString().ToLowerInvariant()}"));

            if (diagnostic.ScarCount > 0)
                details.Add(Loc.GetString("health-analyzer-wound-scars-short", ("count", diagnostic.ScarCount)));

            if (diagnostic.Pain > FixedPoint2.Zero)
                details.Add(Loc.GetString("health-analyzer-wound-pain-short", ("pain", diagnostic.Pain)));

            if (diagnostic.Functionality != BodyPartFunctionalityState.Functional)
                details.Add(Loc.GetString($"health-analyzer-wound-functionality-{diagnostic.Functionality.ToString().ToLowerInvariant()}"));

            if (details.Count > 0)
                AddWoundFinding(Loc.GetString("health-analyzer-wound-part-summary",
                    ("part", partName), ("details", string.Join(" · ", details))));
        }
    }

    internal static bool IsDangerousBloodLevel(float level) => !float.IsNaN(level) && level < DangerousBloodLevel;

    private void AddWoundFinding(string text)
    {
        var label = new RichTextLabel
        {
            MaxWidth = 430,
            HorizontalExpand = true,
            HorizontalAlignment = HAlignment.Left,
            Margin = new Thickness(0, 0, 0, 8),
        };
        label.SetMessage(FormattedMessage.FromMarkupPermissive($"• {text}"));
        WoundFindingsContainer.AddChild(label);
    }

    // <Onyx-HealthAnalyzerChemicals-edited>
    public void SelectBodyTab()
    {
        BodyTab.Visible = true;
        OrgansTab.Visible = false;
        ChemicalsTab.Visible = false; // <Onyx-HealthAnalyzerChemicals>
    }

    public void SelectOrgansTab()
    {
        BodyTab.Visible = false;
        OrgansTab.Visible = true;
        ChemicalsTab.Visible = false; // <Onyx-HealthAnalyzerChemicals>
    }
    // </Onyx-HealthAnalyzerChemicals-edited>

    // <Onyx-HealthAnalyzerChemicals>
    public void SelectChemicalsTab()
    {
        BodyTab.Visible = false;
        OrgansTab.Visible = false;
        ChemicalsTab.Visible = true;
    }

    private void DrawChemicals(HealthAnalyzerUiState state)
    {
        ChemicalsContainer.RemoveAllChildren();

        if (state.ScanMode != true || state.Chemicals == null)
        {
            ChemicalsContainer.AddChild(new Label
            {
                Text = Loc.GetString("health-analyzer-window-chemicals-unavailable"),
            });
            return;
        }

        if (state.Chemicals.Count == 0)
        {
            ChemicalsContainer.AddChild(new Label
            {
                Text = Loc.GetString("health-analyzer-window-chemicals-no-vessels"),
            });
            return;
        }

        foreach (var vessel in state.Chemicals)
        {
            var group = new BoxContainer
            {
                Align = AlignMode.Begin,
                Orientation = LayoutOrientation.Vertical,
            };
            group.AddChild(CreateDiagnosticGroupTitle(
                Loc.GetString($"health-analyzer-window-solution-{vessel.Type.ToString().ToLowerInvariant()}"),
                "metaphysical"));

            if (vessel.Reagents.Count == 0)
            {
                group.AddChild(CreateDiagnosticItemLabel(
                    $" · {Loc.GetString("health-analyzer-window-solution-empty")}"));
            }
            else
            {
                foreach (var reagent in vessel.Reagents.OrderByDescending(reagent => reagent.Quantity))
                {
                    var name = _prototypes.TryIndex(reagent.Prototype, out ReagentPrototype? prototype)
                        ? prototype.LocalizedName
                        : Loc.GetString("chem-master-window-unknown-reagent-text");
                    group.AddChild(CreateDiagnosticItemLabel(
                        $" · {Loc.GetString("health-analyzer-window-solution-reagent", ("reagent", name), ("quantity", reagent.Quantity))}"));
                }
            }

            ChemicalsContainer.AddChild(group);
        }
    }
    // </Onyx-HealthAnalyzerChemicals>

    // <Onyx-HealthAnalyzerOrgans-edited>
    private void DrawOrgans(HealthAnalyzerUiState state)
    {
        if (state.ScanMode != true || state.Organs == null)
        {
            if (_organsUnavailable)
                return;

            ClearOrganRows();
            OrgansContainer.AddChild(new Label
            {
                Text = Loc.GetString("health-analyzer-window-organs-unavailable"),
            });
            _organsUnavailable = true;
            return;
        }

        if (_organsUnavailable)
        {
            OrgansContainer.RemoveAllChildren();
            _organsUnavailable = false;
        }

        var present = new HashSet<NetEntity>();
        var position = 0;
        foreach (var organ in state.Organs.OrderBy(organ => organ.Order))
        {
            if (!_entityManager.TryGetEntity(organ.Entity, out var organEntity) || organ.MaxHealth == 0)
                continue;

            present.Add(organ.Entity);
            var name = _entityManager.HasComponent<MetaDataComponent>(organEntity.Value)
                ? Capitalize(Identity.Name(organEntity.Value, _entityManager))
                : Loc.GetString("health-analyzer-window-entity-unknown-value-text");
            var percent = float.IsFinite((float) organ.Health / (float) organ.MaxHealth)
                ? (int) MathF.Round(Math.Clamp((float) organ.Health / (float) organ.MaxHealth * 100f, 0f, 100f))
                : 0;

            if (_organRows.TryGetValue(organ.Entity, out var existing))
            {
                if (existing.Name.Text != name)
                {
                    existing.Name.Text = name;
                    existing.Name.ToolTip = name;
                }

                var health = Loc.GetString("health-analyzer-window-organ-health", ("percent", percent));
                if (existing.Health.Text != health)
                    existing.Health.Text = health;

                if (existing.Row.GetPositionInParent() != position)
                    existing.Row.SetPositionInParent(position);
                position++;
                continue;
            }

            var row = new BoxContainer
            {
                Orientation = LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                SeparationOverride = 8,
            };
            var icon = new SpriteView
            {
                SetSize = new Vector2(26, 26),
                OverrideDirection = Direction.South,
            };
            icon.SetEntity(organEntity.Value);
            row.AddChild(icon);
            var nameLabel = new EllipsisLabel
            {
                HorizontalExpand = true,
                Text = name,
                ToolTip = name,
            };
            row.AddChild(nameLabel);
            var healthLabel = new Label
            {
                Text = Loc.GetString("health-analyzer-window-organ-health",
                    ("percent", percent)),
            };
            row.AddChild(healthLabel);
            OrgansContainer.AddChild(row);
            row.SetPositionInParent(position++);
            _organRows[organ.Entity] = (row, nameLabel, healthLabel);
        }

        foreach (var entity in _organRows.Keys.Where(entity => !present.Contains(entity)).ToArray())
        {
            OrgansContainer.RemoveChild(_organRows[entity].Row);
            _organRows.Remove(entity);
        }
    }

    private void ClearOrganRows()
    {
        OrgansContainer.RemoveAllChildren();
        _organRows.Clear();
        _organsUnavailable = false;
    }

    private static string Capitalize(string text) =>
        string.IsNullOrEmpty(text) ? text : OopsConcat(char.ToUpper(text[0]).ToString(), text.Remove(0, 1));

    private static string OopsConcat(string first, string rest)
    {
        // Prevent Roslyn from emitting string span code forbidden by the content sandbox.
        return first + rest;
    }
    // </Onyx-HealthAnalyzerOrgans-edited>
    // </Onyx-HealthAnalyzer-StatusDoll>

    private static string GetStatus(MobState mobState)
    {
        return mobState switch
        {
            MobState.Alive => Loc.GetString("health-analyzer-window-entity-alive-text"),
            MobState.Critical => Loc.GetString("health-analyzer-window-entity-critical-text"),
            MobState.Dead => Loc.GetString("health-analyzer-window-entity-dead-text"),
            _ => Loc.GetString("health-analyzer-window-entity-unknown-text"),
        };
    }

    private void DrawDiagnosticGroups(
        Dictionary<ProtoId<DamageGroupPrototype>, FixedPoint2> groups,
        IReadOnlyDictionary<ProtoId<DamageTypePrototype>, FixedPoint2> damageDict)
    {
        GroupsContainer.RemoveAllChildren();

        foreach (var (damageGroupId, damageAmount) in groups)
        {
            if (damageAmount == 0)
                continue;

            var groupTitleText = $"{Loc.GetString(
                "health-analyzer-window-damage-group-text",
                ("damageGroup", _prototypes.Index<DamageGroupPrototype>(damageGroupId).LocalizedName),
                ("amount", damageAmount)
            )}";

            var groupContainer = new BoxContainer
            {
                Align = AlignMode.Begin,
                Orientation = LayoutOrientation.Vertical,
            };

            groupContainer.AddChild(CreateDiagnosticGroupTitle(groupTitleText, damageGroupId));

            GroupsContainer.AddChild(groupContainer);

            // Show the damage for each type in that group.
            var group = _prototypes.Index<DamageGroupPrototype>(damageGroupId);

            foreach (var type in group.DamageTypes)
            {
                if (!damageDict.TryGetValue(type, out var typeAmount) || typeAmount <= 0)
                    continue;

                var damageString = Loc.GetString(
                    "health-analyzer-window-damage-type-text",
                    ("damageType", _prototypes.Index<DamageTypePrototype>(type).LocalizedName),
                    ("amount", typeAmount)
                );

                groupContainer.AddChild(CreateDiagnosticItemLabel(damageString.Insert(0, " · ")));
            }
        }
    }

    private Texture GetTexture(string texture)
    {
        var rsiPath = new ResPath("/Textures/Objects/Devices/health_analyzer.rsi");
        var rsiSprite = new SpriteSpecifier.Rsi(rsiPath, texture);

        var rsi = _cache.GetResource<RSIResource>(rsiSprite.RsiPath).RSI;
        if (!rsi.TryGetState(rsiSprite.RsiState, out var state))
        {
            rsiSprite = new SpriteSpecifier.Rsi(rsiPath, "unknown");
        }

        return _spriteSystem.Frame0(rsiSprite);
    }

    private static Label CreateDiagnosticItemLabel(string text)
    {
        return new Label
        {
            Text = text,
        };
    }

    private BoxContainer CreateDiagnosticGroupTitle(string text, string id)
    {
        var rootContainer = new BoxContainer
        {
            Margin = new Thickness(0, 6, 0, 0),
            VerticalAlignment = VAlignment.Bottom,
            Orientation = LayoutOrientation.Horizontal,
        };

        rootContainer.AddChild(new TextureRect
        {
            SetSize = new Vector2(30, 30),
            Texture = GetTexture(id.ToLower())
        });

        rootContainer.AddChild(CreateDiagnosticItemLabel(text));

        return rootContainer;
    }
}
