using Content.Client.UserInterface.Controls;
using Content.Shared.MedicalScanner;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls; // <Onyx-HealthAnalyzer-Interface>
using Robust.Client.UserInterface.XAML;

namespace Content.Client.HealthAnalyzer.UI;

[GenerateTypedNameReferences]
public sealed partial class HealthAnalyzerWindow : FancyWindow
{
    public HealthAnalyzerWindow()
    {
        RobustXamlLoader.Load(this);
        // <Onyx-HealthAnalyzer-Interface-edited>
        BodyButton.OnPressed += _ => SelectTab(BodyButton, HealthAnalyzer.SelectBodyTab);
        OrgansButton.OnPressed += _ => SelectTab(OrgansButton, HealthAnalyzer.SelectOrgansTab);
        ChemicalsButton.OnPressed += _ => SelectTab(ChemicalsButton, HealthAnalyzer.SelectChemicalsTab);
        // </Onyx-HealthAnalyzer-Interface-edited>
    }

    public void Populate(HealthAnalyzerScannedUserMessage msg)
    {
        HealthAnalyzer.Populate(msg.State);
        // <Onyx-HealthAnalyzer-Interface>
        TabButtons.Visible = HealthAnalyzer.IsHumanoid;
        if (!HealthAnalyzer.IsHumanoid)
            SelectTab(BodyButton, HealthAnalyzer.SelectBodyTab);
        // </Onyx-HealthAnalyzer-Interface>
    }

    // <Onyx-HealthAnalyzer-Interface>
    private void SelectTab(Button selected, Action select)
    {
        BodyButton.Pressed = BodyButton == selected;
        OrgansButton.Pressed = OrgansButton == selected;
        ChemicalsButton.Pressed = ChemicalsButton == selected;
        select();
    }
    // </Onyx-HealthAnalyzer-Interface>
}
