// SPDX-FileCopyrightText: 2026 Space Onyx Contributors
// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Numerics;
using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared._Onyx.ReadyManifest;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Onyx.ReadyManifest;

[GenerateTypedNameReferences]
public sealed partial class ReadyManifestWindow : DefaultWindow
{
    [Dependency] private IPrototypeManager _prototypes = default!;
    [Dependency] private IEntitySystemManager _systems = default!;

    private SpriteSystem _sprites = default!;

    public ReadyManifestWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _sprites = _systems.GetEntitySystem<SpriteSystem>();
    }

    public void Populate(ReadyManifestEntry[] entries)
    {
        ManifestContainer.DisposeAllChildren();

        if (entries.Length == 0)
        {
            ManifestContainer.AddChild(new Label
            {
                Text = Loc.GetString("ready-manifest-empty"),
                HorizontalAlignment = HAlignment.Center,
            });
            return;
        }

        var departments = _prototypes.EnumeratePrototypes<DepartmentPrototype>()
            .Where(department => !department.EditorHidden)
            .OrderBy(department => department, DepartmentUIComparer.Instance)
            .ToArray();

        foreach (var department in departments)
        {
            var jobs = department.Roles
                .Where(job => entries.Any(entry => entry.Job == job))
                .Select(job => _prototypes.Index(job))
                .ToList();

            if (jobs.Count == 0)
                continue;

            if (JobUIComparer.TryCreate(_prototypes, null, out var comparer))
                jobs.Sort(comparer);

            var section = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                HorizontalExpand = true,
            };
            var stripe = new StripeBack();
            stripe.AddChild(new Label
            {
                Text = Loc.GetString(department.Name),
                StyleClasses = { "LabelBig" },
                Align = Label.AlignMode.Center,
            });
            section.AddChild(stripe);

            foreach (var job in jobs)
            {
                AddJob(section, job, entries.Where(entry => entry.Job == job).ToArray());
            }

            ManifestContainer.AddChild(section);
        }
    }

    private void AddJob(BoxContainer section, JobPrototype job, ReadyManifestEntry[] entries)
    {
        var jobContainer = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
        };
        var heading = new GridContainer
        {
            HorizontalExpand = true,
            Columns = 2,
        };
        var title = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
        };
        title.AddChild(new TextureRect
        {
            Texture = _sprites.Frame0(_prototypes.Index(job.Icon).Icon),
            TextureScale = new Vector2(2, 2),
            VerticalAlignment = VAlignment.Center,
            Margin = new Thickness(0, 0, 4, 0),
        });
        title.AddChild(new Label
        {
            Text = job.LocalizedName + ":",
            HorizontalExpand = true,
            VerticalAlignment = VAlignment.Center,
        });
        heading.AddChild(title);
        heading.AddChild(new Label
        {
            Text = entries.Length.ToString(),
            HorizontalExpand = true,
            VerticalAlignment = VAlignment.Center,
        });
        jobContainer.AddChild(heading);

        var names = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
            Margin = new Thickness(20, 0, 0, 5),
        };

        foreach (var entry in entries
                     .OrderByDescending(entry => entry.Priority)
                     .ThenBy(entry => entry.CharacterName, StringComparer.CurrentCultureIgnoreCase))
        {
            names.AddChild(new Label
            {
                Text = "• " + entry.CharacterName,
                FontColorOverride = Color.LightGray,
            });
        }

        jobContainer.AddChild(names);
        section.AddChild(jobContainer);
    }
}
