# SPDX-FileCopyrightText: 2024 Aidenkrz <aiden@djkraz.com>
# SPDX-FileCopyrightText: 2024 Piras314 <p1r4s@proton.me>
# SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

- type: job
  id: RadioHost
  name: job-name-radiohost
  description: job-description-radiohost
  playTimeTracker: JobRadioHost
  startingGear: RadioHostGear
  icon: JobIconRadioHost
  supervisors: job-supervisors-hop
  contracts:
  - DocumentContractEmploymentService
  access:
  - Maintenance
  - Journalism
  - Service

- type: startingGear
  id: RadioHostGear
  equipment:
    ears: ClothingHeadsetAltRadioHost
    belt: ClothingBeltStorageWaistbag
    shoes: ClothingShoesColorBlack
    id: RadioHostPDA
