using System.Numerics;
using System.Linq;
using Content.Shared.VendingMachines;
using Content.Shared.VendingMachines.Components;
using Content.Shared._Onyx.Salvage.MiningPoints;
using Content.Shared._Onyx.Bitrunning.Components;
using Content.Shared.Access.Systems;
using Content.Client.Access;
using Content.Client.Chemistry.Containers.EntitySystems;
using Robust.Client.Player;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using FancyWindow = Content.Client.UserInterface.Controls.FancyWindow;
using Robust.Client.UserInterface;
using Content.Client.UserInterface.Controls;
using Content.Shared.IdentityManagement;
using Content.Shared.Chemistry;
using Content.Shared.Chemistry.Components;
using Robust.Client.Graphics;
using System.Text;
using Robust.Shared.Timing;

namespace Content.Client._Onyx.VendingMachines.UI;

[GenerateTypedNameReferences]
[Virtual]
public partial class FancyVendingMachineMenu : FancyWindow
{
    [Dependency] private IPrototypeManager _prototypeManager = default!;
    [Dependency] private IEntityManager _entityManager = default!;
    [Dependency] private IPlayerManager _playerManager = default!;
    [Dependency] private IGameTiming _gameTiming = default!;

    private const uint SolutionAppearanceWarmupFrames = 3;
    private readonly Dictionary<EntProtoId, EntityUid> _dummies = [];
    private readonly List<FancyVendingMachineData> _cachedItems = [];
    private readonly List<(EntityUid Entity, uint Frame)> _pendingSolutionAppearances = [];

    public event Action<VendingMachineInventoryEntry>? OnItemSelected;
    public Action? OnWithdraw;

    private double _priceMultiplier = 1;
    private bool _infiniteStock;
    private bool _ejecting;
    protected bool UsesIdCardMiningPoints;
    protected bool UsesBitrunningPoints;
    private int _credits;
    private string _balanceLabel = string.Empty;
    private readonly SharedIdCardSystem _idCardSystem;
    private readonly SolutionContainerSystem _solution;

    public Color ButtonBorderColor = Color.FromHex("#4972A1");
    public Color ButtonBaseColor = Color.FromHex("#141F2F");
    public Color ButtonHoveredColor = Color.FromHex("#4972A1");
    public Color ButtonDisabledColor = Color.FromHex("#3f3f3fff");

    public FancyVendingMachineMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        DarkBackground.PanelOverride = new StyleBoxFlat { BackgroundColor = Color.FromHex("#141519") };
        _idCardSystem = _entityManager.System<IdCardSystem>();
        _solution = _entityManager.System<SolutionContainerSystem>();
        SearchBar.OnTextChanged += _ => PopulateList();
        WithdrawButton.OnPressed += _ => OnWithdraw?.Invoke();
    }

    public override void Close()
    {
        base.Close();

        // Delete any dummy items we spawned
        foreach (var entity in _dummies.Values)
        {
            _entityManager.QueueDeleteEntity(entity);
        }
        _dummies.Clear();
        _pendingSolutionAppearances.Clear();
    }

    private bool DataFilterCondition(string filter, FancyVendingMachineData data)
    {
        if (string.IsNullOrEmpty(filter))
            return true;

        return data.Name.Contains(filter, StringComparison.CurrentCultureIgnoreCase);
    }

    /// <summary>
    /// Populates the list of available items on the vending machine interface
    /// and sets icons based on their prototypes
    /// </summary>
    public void Populate(EntityUid entityUid, List<VendingMachineInventoryEntry> inventory, double priceMultiplier, int credits,
        bool showWithdraw, string balanceLabel, bool infiniteStock, bool usesIdCardMiningPoints = false,
        bool usesBitrunningPoints = false)
    {
        _cachedItems.Clear();
        _infiniteStock = infiniteStock;
        UsesIdCardMiningPoints = usesIdCardMiningPoints;
        UsesBitrunningPoints = usesBitrunningPoints;
        _balanceLabel = balanceLabel;
        _credits = usesIdCardMiningPoints ? GetLocalPoints() : credits;
        _priceMultiplier = _entityManager.GetComponentOrNull<VendingMachineComponent>(entityUid)?.AllForFree ?? true ? 0 : priceMultiplier;

        if (_entityManager.TryGetComponent<VendingMachineComponent>(entityUid, out var comp))
        {
            ButtonBaseColor = comp.UiButtonBaseColor;
            ButtonBorderColor = comp.UiButtonBorderColor;
            ButtonHoveredColor = comp.UiButtonHoveredColor;
            ButtonDisabledColor = comp.UiButtonDisabledColor;
        }

        CreditsLabel.Text = Loc.GetString(balanceLabel, ("credits", _credits));
        WithdrawButton.Visible = showWithdraw;
        WithdrawButton.Disabled = _credits == 0;

        if (inventory.Count == 0 && VendingContents.Visible)
        {
            SearchBar.Visible = false;
            VendingContents.Visible = false;

            var outOfStockLabel = new Label()
            {
                Text = Loc.GetString("vending-machine-component-try-eject-out-of-stock"),
                Margin = new Thickness(4, 4),
                HorizontalExpand = true,
                VerticalAlignment = VAlignment.Stretch,
                HorizontalAlignment = HAlignment.Center
            };

            MainContainer.AddChild(outOfStockLabel);

            return;
        }

        for (var i = 0; i < inventory.Count; i++)
        {
            var entry = inventory[i];

            if (!_dummies.TryGetValue(entry.ID, out var dummy))
            {
                dummy = _entityManager.Spawn(entry.ID);
                _dummies.Add(entry.ID, dummy);
                _pendingSolutionAppearances.Add((dummy, _gameTiming.CurFrame + SolutionAppearanceWarmupFrames));
            }

            StringBuilder sb = new(entry.OverrideName == null
                ? Identity.Name(dummy, _entityManager)
                : Loc.GetString(entry.OverrideName));
            sb[0] = char.ToUpper(sb[0]);

            _cachedItems.Add(new FancyVendingMachineData(sb.ToString(), entry));
        }

        PopulateList();
    }

    private void PopulateList()
    {
        VendingContents.RemoveAllChildren();

        var filter = SearchBar.Text;
        var filtered = _cachedItems.Where(item => DataFilterCondition(filter, item)).ToList();

        if (filtered.All(item => item.Entry.Category == null))
        {
            var grid = CreateGrid();
            VendingContents.AddChild(grid);
            AddItems(grid, filtered);
            return;
        }

        filtered = filtered.OrderBy(item => item.Entry.Order).ToList();

        foreach (var category in filtered.Select(item => item.Entry.Category).Distinct())
        {
            var items = filtered.Where(item => item.Entry.Category == category).ToList();

            var header = CreateCategoryHeader(category == null
                ? Loc.GetString("vending-ui-category-other")
                : Loc.GetString(category));
            VendingContents.AddChild(header);

            var grid = CreateGrid();
            VendingContents.AddChild(grid);
            AddItems(grid, items);
        }
    }

    public void SetEjecting(bool ejecting)
    {
        if (_ejecting == ejecting)
            return;

        _ejecting = ejecting;
        PopulateList();
    }

    protected virtual Control CreateCategoryHeader(string text)
    {
        var panel = new PanelContainer
        {
            Margin = new Thickness(8, 12, 8, 4),
            HorizontalExpand = true,
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = Color.FromHex("#292c32"),
                BorderColor = Color.FromHex("#4b515b"),
                BorderThickness = new Thickness(1),
                ContentMarginLeftOverride = 8,
                ContentMarginRightOverride = 8,
                ContentMarginTopOverride = 4,
                ContentMarginBottomOverride = 4,
            },
        };
        panel.AddChild(new Label { Text = text, StyleClasses = { "LabelHeading" } });
        return panel;
    }

    private static GridContainer CreateGrid()
    {
        return new GridContainer
        {
            Columns = 6,
            HorizontalExpand = true,
            HorizontalAlignment = HAlignment.Left,
        };
    }

    private void AddItems(GridContainer grid, List<FancyVendingMachineData> items)
    {
        foreach (var item in items)
        {
            var price = (int)(item.Entry.Price * _priceMultiplier);
            var affordable = !_ejecting && (!UsesIdCardMiningPoints || price <= _credits);
            var listItem = new FancyVendingMachineItem(_dummies[item.Entry.ID], item.Name, (int)item.Entry.Amount, price,
                _infiniteStock, affordable, UsesIdCardMiningPoints);
            listItem.BuyPressed += () => OnItemSelected?.Invoke(item.Entry);

            grid.AddChild(listItem);
        }
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        for (var i = _pendingSolutionAppearances.Count - 1; i >= 0; i--)
        {
            var pending = _pendingSolutionAppearances[i];
            if (_gameTiming.CurFrame < pending.Frame)
                continue;

            _pendingSolutionAppearances.RemoveAt(i);
            if (_entityManager.EntityExists(pending.Entity))
                ApplySolutionAppearance(pending.Entity);
        }

        if (!UsesIdCardMiningPoints)
            return;

        var credits = GetLocalPoints();
        if (credits == _credits)
            return;

        _credits = credits;
        CreditsLabel.Text = Loc.GetString(_balanceLabel, ("credits", _credits));
        PopulateList();
    }

    private int GetLocalPoints()
    {
        if (_playerManager.LocalEntity is not { } player ||
            !_idCardSystem.TryFindIdCard(player, out var card))
        {
            return 0;
        }

        if (UsesBitrunningPoints && _entityManager.TryGetComponent<BitrunningPointsComponent>(card, out var bitrunningPoints))
            return (int) Math.Min(bitrunningPoints.Points, int.MaxValue);

        if (!UsesBitrunningPoints && _entityManager.TryGetComponent<MiningPointsComponent>(card, out var miningPoints))
            return miningPoints.Points;

        return 0;
    }

    private void ApplySolutionAppearance(EntityUid entity)
    {
        if (!_entityManager.TryGetComponent(entity, out AppearanceComponent? appearance))
            return;

        Entity<SolutionComponent>? solutionEntity = null;
        foreach (var entry in _solution.EnumerateSolutions((entity, null)))
        {
            if (entry.Solution.Comp.Solution.Volume <= 0)
                continue;

            solutionEntity = entry.Solution;
            break;
        }

        if (solutionEntity == null)
            return;

        var solution = solutionEntity.Value.Comp.Solution;
        var appearanceSystem = _entityManager.System<SharedAppearanceSystem>();
        appearanceSystem.SetData(entity, SolutionContainerVisuals.FillFraction, solution.FillFraction, appearance);
        appearanceSystem.SetData(entity, SolutionContainerVisuals.Color, solution.GetColor(_prototypeManager), appearance);
        appearanceSystem.SetData(entity, SolutionContainerVisuals.SolutionName, solutionEntity.Value.Comp.Id, appearance);

        if (solution.GetPrimaryReagentId() is { } reagent)
            appearanceSystem.SetData(entity, SolutionContainerVisuals.BaseOverride, reagent.ToString(), appearance);
    }

    private record struct FancyVendingMachineData(string Name, VendingMachineInventoryEntry Entry);
}

public sealed class SalvageVendingMachineMenu : FancyVendingMachineMenu
{
    public SalvageVendingMachineMenu()
    {
        FooterLeft.Text = Loc.GetString("salvage-vending-machine-footer");
        FooterRight.Text = "2.0";
    }
}
