- type: job
  id: SeniorResearcher
  name: job-name-senior-researcher
  description: job-description-senior-researcher
  playTimeTracker: JobSeniorResearcher
  requirements:
    - !type:DepartmentTimeRequirement
      department: Science
      time: 60h
  startingGear: SeniorResearcherGear
  icon: "JobIconSeniorResearcher"
  supervisors: job-supervisors-rd
  # <Onyx-Contracts>
  contracts:
  - DocumentContractEmploymentRnd
  # </Onyx-Contracts>
  access:
  - Research
  - Maintenance

- type: startingGear
  id: SeniorResearcherGear
  equipment:
    shoes: ClothingShoesColorBlack
    id: SeniorResearcherPDA
    ears: ClothingHeadsetScience

- type: chameleonOutfit
  id: SeniorResearcherChameleonOutfit
  job: SeniorResearcher
  equipment:
    head: ClothingHeadHatBeretRND
    eyes: ClothingEyesGlassesCheapSunglasses
    mask: ClothingMaskGas
    tie: ClothingNeckTieSci # <Onyx-InventorySubslots-edited>
    outerClothing: ClothingOuterCoatLabSeniorResearcher
    gloves: ClothingHandsGlovesLatex
